### PR TITLE
feat: Add configuration for hostname truncation

### PR DESCRIPTION
**Pull request by zekesonxx**
#### Description
Added the simple ability to trim some text off the end of the hostname. Ex: `server.example.com`, if `trim_end=".example.com"`, can become just `server`

#### Motivation and Context
I would like to use starship for my work shell prompt, but having `servername.asdf.example.com` show up takes up a *lot* of space, and it needs to get trimmed down to `servername`.

I could trim it to the first dot (which is what bash and zfs like doing, and might not be a bad additional feature), except that some of my work machines are `desktop.servername.asdf.example.com` or `speedtest.servername.asdf.example.com`, and just having `desktop` or `speedtest` show up is annoying because I don't know *which* one I'm connected to

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by matchai** [comment]
Perhaps we could unify the two features you mentioned:
- Trimming the hostname
- Trimming to the first dot

If instead of `trim_end`, it could act as a `trim_from` or `trim_at`, trimming the remaining hostname once the value is matched.

```toml
[hostname]
# Input: speedtest.servername.asdf.example.com
trim_from = "."
# Output: speedtest

[hostname]
# Input: speedtest.servername.asdf.example.com
trim_from = ".asdf.example.com"
# Output: speedtest.servername
```

What are your thoughts, @zekesonxx?

**Comment by zekesonxx** [comment]
@matchai that seems reasonable. Let me see if I can implement that...

**Comment by zekesonxx** [comment]
Okay, so, `trim_at` implemented.

A selection of example results, as based on the hostname `speedtest.cluster.asdf.example.com`:
* `.`: `speedtest` (this is what bash and zsh do by default, and is now the default here too)
* `.asdf`: `speedtest.cluster`
* `.asdf.example.com`: `speedtest.cluster`
* `.example.com`: `speedtest.cluster.asdf`
* `t`: `speed`
* `e`: `sp`
* `ee`: `sp`

**Comment by matchai** [comment]
Thank you for your contribution, Zach! 😄 

@all-contributors Please add @zekesonxx for code, docs, and test.

**Pull request merged**
