### PR TITLE
feat: Add OS symbol for Kali Linux

### PR DESCRIPTION
**Pull request by silopolis**
#### Description

Add Kali Linux to the list of supported OS symbols.

I have mostly used the "㉿" symbol that Kali itself uses for its prompts, except where I used "" because I don't know how to find the UTF code of the first symbol :/
Someday, I manage to get my head around all of these encoding and stuff...
If s/o can help me with this, I'll gladly update this PR for consistency
 
#### Checklist:
- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
  I guiltfully confess I didn't test this because I have no Rust env setup and was both lazy and short on time to tackle this. I'm sorry for that. I hope this will be acceptable for such a PR :pray: :crossed_fingers:

### CODE REVIEW

**Comment by silopolis** [comment]
Well, sadly, it looks like I'm missing something... If you guys could point me into the right direction to make CI happy, that'd be gratefully appreciated :pray: 

Thanks in advance
TY
J

**Comment by davidkna** [comment]
The crate we use for this, `os_info` has support for Kali Linux, but it appears a stable version supporting Kali Linux hasn't been released yet.

**Comment by silopolis** [comment]
Meaning, the CI doesn't use the crate with kali support?
Should I do something with this PR? Or is it just simply useless? 😭😅

**Comment by davidkna** [comment]
The crate version that supports kali detection hasn't been released yet. We can revisit this PR once it has.

**Comment by silopolis** [comment]
OK, perfect!
Please don't hesitate to ping me if I miss the news...
Have a nice one
J

**Pull request closed without merging**
