### PR TITLE
docs: Added the xonsh shell section

### LINKED ISSUE #272: Support for the xonsh shell
If it is possible to combine starship with the Python-based shell [xonsh](https://xon.sh/tutorial.html), I think the result would be awesome.

### PR DESCRIPTION
**Pull request by anki-code**
Closes #272

#### Description

The xonsh shell has the pretty tested and full featured support of Starship. I've added the section about how to initilize this in xonsh to the docs.

#### Motivation and Context

The xonsh users like the Starship support in xonsh. The xonsh section will help Starship grow.

#### Screenshots (if appropriate):

image

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by andytom** [comment]
Does this replace #1265?

**Comment by anki-code** [comment]
hi @andytom! 
Yes, this closes #272.
The solution from #1265 is to put the xonsh code to the starship. This PR provides the way to connect starship to xonsh without adding xonsh code to the starship.
I suggest to merge this PR now and then merge #1265 when the work will be fully completed if you will want to support xonsh code.

**Comment by andytom** [comment]
Sounds good to me is there any limitations with this approach? @vladimyr since you worked on the other PR do you have any options?

**Comment by anki-code** [comment]
The approach to get starship in xonsh is the same. This PR is just use xonsh extension that should be installed via pip. The #1265 issue brings almost the same approach like in xonsh extension but inside the starship.

**Pull request closed without merging**
