### PR TITLE
Respect status.showUntrackedFiles

### PR DESCRIPTION
**Pull request by oblitum**
#### Is your feature request related to a problem? Please describe.

On some repository I have `git config status.showUntrackedFiles no` but when there are untracked files in this repository I still get a permanent `[?]` in the prompt.

#### Describe the solution you'd like

I think `showUntrackedFiles` should be respected, and when it's set to `no`, then the prompt should follow it.

#### Describe alternatives you've considered

None.

### CODE REVIEW

**Comment by oblitum** [comment]
I've converted the issue into a pull request.

**Comment by oblitum** [comment]
Sorry, test setup is too annoying for me, so I won't add the test.

**Comment by oblitum** [comment]
Nice! Sorry for not adding the test, besides not having my machine read to set it up, I'm not familiar writing one of these either, so your code served me as a reference.

**Comment by matchai** [comment]
No worries! Happy to help. 👍 
@all-contributors Please add @oblitum for code.

**Pull request merged**
