### PR TITLE
fix(status): Make status module work even when the status is 0

### LINKED ISSUE #3746: success_symbol option of the status module is being ignored
#### Current Behavior
`success_symbol` option of the `status` module is being ignored.

#### Expected Behavior
Show the `success_symbol` when command succeed as describe in the [documentation](https://starship.rs/config/#options-61): "The symbol displayed on program success"

#### Additional context/Screenshots

```
 ❯ sh -c 'echo tst; exit 0;'                               
tst

 ❯ sh -c 'echo tst; exit 7;'                               
tst

 ❯                                                    ✗ [7]
```

#### Possible Solution

ATM IDK.  I will update this issue, if I come up with something.

#### Environment
- Starship version: `starship 1.4.2 branch: commit_hash: build_time:2022-03-10 18:01:38 +00:00 build_env:rustc 1.59.0`
- Shell type: zsh
- Shell version: `zsh 5.8 (x86_64-apple-darwin21.0)`
- Shell plugin manager: nothing
- Terminal emulators: iTerm and Alacritty
- Operating system: MacOS 12.2.1

#### Relevant Shell Configuration

```
~
❯ cat ~/.zshrc
eval "$(starship init zsh)"
```

#### Starship Configuration

```toml
format = " $character"
right_format = "$status "

[character]
success_symbol = "[❯](bold green)"
error_symbol   = "[❯](bold green)"
vicmd_symbol   = "[❮](bold green)"

[status]
style = "fg:blue"
symbol = "[✗](bold red)"
success_symbol = "[✔️](bold green)"
format = '$symbol$success_symbol [\[$int\]]($style) '
disabled = false
```

### PR DESCRIPTION
**Pull request by IzhakJakov**
#### Description

Modify `status` module work even when the status is 0

#### Motivation and Context

Closes #3746 and enables a potential workaround for #2967 as well.

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by IzhakJakov** [comment]
I can test on Linux but don't have access to a Windows machine ATM.

**Comment by IzhakJakov** [comment]
I see.  I'll do it soon thanks

**Comment by IzhakJakov** [comment]
It's complaining that I fixed indentation?
-- I'll just revert that part then...

**Review by matchai — APPROVED** [review]
LGTM! 👍

Thank you for your contribution @IzhakJakov and for the review @andytom! 😄

**Comment by IzhakJakov** [comment]
Thank you :)

**Pull request merged**
