### PR TITLE
docs: Add vuepress with initial docs

### PR DESCRIPTION
**Pull request by sirMerr**
#### Description

Uses [Vuepress](https://vuepress.vuejs.org/) for our documentation with a basic layout and information on how to do configuration. ~A few of the sections are still incomplete.~
 
#### Motivation and Context

We want to start adding our modules and segments, and this is a good place to do it.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Screenshots (if appropriate):
image

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by matchai** [comment]
It looks to me like most of these files are built output. I think we may want to `.gitignore` the `docs/book/` files and build them as part of CI, since we'll be hosting them anyway on GH Pages or Netlify. 😄

**Comment by sirMerr** [comment]
Oops I forgot to add to our gitignore haha, will do!

**Comment by matchai** [comment]
Netlify doesn't seem to be building the new docs in CI correctly, but here's what they look like at the moment:
https://objective-pike-5b0e40.netlify.com/

**Comment by matchai** [comment]
@all-contributors please add @sirMerr for doc

**Comment by matchai** [comment]
@all-contributors please add @sirMerr for docs

**Pull request merged**
