### PR TITLE
docs: Simplify installation process and docs

### PR DESCRIPTION
**Pull request by matchai**
#### Description

Add a one-line installer for starship. For the time being, it will install the latest suitable version for the user's platform and architecture.

I also took the opportunity to clean up the installation docs, which have recently gotten cluttered, giving the impression that we have a lengthy installation process at a glance. 

[**📝 Click here to view the new README.md**](https://github.com/starship/starship/blob/update-install/README.md)

#### Motivation and Context

Closes #

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by gkmngrgn** [comment]
@matchai Hi,

I tried to install starship with your install.sh script but there's a problem about an unknown parameter.

### My System
- Ubuntu 19.10 (Eoan)
- Shell: BASH

### Output
```shell
django-formtools on  master
❯ curl -fsSL https://raw.githubusercontent.com/starship/starship/a59e939fdc187f18d80960a3b964ccba6b60b1d0/install/install.sh | sh
sh: 3: set: Illegal option -o pipefail

django-formtools on  master
❯ curl -fsSL https://raw.githubusercontent.com/starship/starship/a59e939fdc187f18d80960a3b964ccba6b60b1d0/install/install.sh | bash
  Configuration
> Bin directory: /usr/local/bin
> Platform:      unknown-linux-gnu
> Arch:          x86_64

> Tarball URL: https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
? Install Starship latest to /usr/local/bin? [yN]
```

**And a quick feature request:** Is it possible to install starship without any question on the prompt? Maybe we can add a parameter like "--noinput" for using default selections? I want to add a simple code like "If starship executable file doesn't exist, download it here at first.":

https://github.com/gkmngrgn/config/blob/master/.bash_profile#L34-L35

Thank you.

**Comment by matchai** [comment]
> Maybe we can add a parameter like "--noinput" for using default selections?

The flag is available here: https://github.com/starship/starship/blob/a59e939fdc187f18d80960a3b964ccba6b60b1d0/install/install.sh#L173

**Comment by matchai** [comment]
The install script can be tested on the Netlify deployment:
```sh
curl -fsSL http://deploy-preview-643--starship-rs.netlify.com/install.sh | sh
```

**Comment by nickwb** [comment]
Works great on MacOS 10.14!

**Pull request merged**
