### PR TITLE
feat(deno): detect `deno.json` and `deno.jsonc`

### PR DESCRIPTION
**Pull request by maximousblk**
#### Description

add `deno.json` and `deno.jsonc` to default detected files list

#### Motivation and Context

Deno added support for config files in `1.14` and suggest using `deno.json` and `deno.jsonc` as file names in the [Deno Manual](https://deno.land/manual/getting_started/configuration_file)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by chipbuster** [comment]
@maximousblk Is this ready for review? It's still marked as draft right now, so I can't review it.

**Comment by maximousblk** [comment]
sorry i forgot about this 😅. i'll update it in a bit

**Comment by maximousblk** [comment]
@chipbuster it's ready now

**Comment by matchai** [comment]
@maximousblk could you please undo the changes to the non-English docs.
Those files are auto-generated by Crowdin, so making changes to them is likely to cause conflicts down the line.

**Comment by maximousblk** [comment]
done 👍

**Review by chipbuster — APPROVED** [review]
:+1: LGTM.

**Comment by andytom** [comment]
Thank you for your contribution @maximousblk and thanks for the review @chipbuster and @matchai.

**Pull request merged**
