### PR TITLE
fix: Don't include `.app` in terminal name

### PR DESCRIPTION
**Pull request by johnletey**
#### Description

I personally use iTerm as my terminal emulator. When running `echo $TERM_PROGRAM`, I receive `iTerm.app`. This output is used in the `bug-report` command. We would just ideally want `iTerm`. The code now concatenates the `.app` off of the output, if it exists.

#### Motivation and Context

Closes #

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by johnletey** [comment]
@matchai / @starship/astronauts Is there a reason why the tests passed in the first commit, but not in the second?

**Comment by matchai** [comment]
Please don't `@` everyone for CI failing.
The dotnet tests are flakey and occasionally fail. They need to be reworked.

**Comment by johnletey** [comment]
> Please don't `@` everyone for CI failing.

Noted! Apologise for the spam folks!

> The dotnet tests are flakey and occasionally fail. They need to be reworked.

Understand, so nothing that I need to do on my end.

**Comment by johnletey** [comment]
Closing in favour of #787.

**Pull request closed without merging**
