### PR TITLE
docs: Add entry for Nushell configuration.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
#### Description
Add a listing for Nushell, which pairs beautifully with Starship!

#### Motivation and Context
Nushell and Starship go together like peanut butter and honey.

#### How Has This Been Tested?
I've been using this configuration for months on my work Mac. It is also listed as the way to incorporate Starship in Nushell's official documentation.
- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:
- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by andytom** [comment]
I am not sure this is actually needed, I thought starship was built into nushell by default see https://www.nushell.sh/blog/2019/11/26/nushell-0_6_0.html.

**Comment by ryanpcmcquen** [comment]
@andytom, that is no longer true:
https://www.nushell.sh/blog/2020/09/01/nushell_0_19.html#starship-is-now-external

**Comment by andytom** [comment]
> @andytom, that is no longer true:
> https://www.nushell.sh/blog/2020/09/01/nushell_0_19.html#starship-is-now-external

Ah you are correct I haven't been been keeping up with the latest releases of Nu. In that case I think this might need more work since as pointed out in #1716, you will need to add the `--status` argument to get the character module to work correctly.

**Comment by andytom** [comment]
I've converted this PR back to a draft as there is still some further work required (see #1716)

**Pull request closed without merging**
