### PR TITLE
WIP: PowerShell

### LINKED ISSUE #126: Add prompt support for PowerShell
## Feature Request
Support for [PowerShell](https://github.com/PowerShell/PowerShell) would be extra cool!

I'd be more than happy to put together a pull request for this.

#### Is your feature request related to a problem? Please describe.
Cannot use Starship if workflow is mainly with PowerShell

#### Describe the solution you'd like
Add support for PowerShell for the Starship prompt

#### Describe alternatives you've considered
Using zsh/fish via [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about), and invoking powershell scripts from there. But obviously not as nice as having it in PS

### PR DESCRIPTION
**Pull request by jmercha**
Adds support for powershell prompt #126

#### Description
This MR adds support for using the starship prompt within powershell.

#### Motivation and Context

PowerShell is a popular shell for Windows, as well as on Linux and macOS with PowerShell Core.

Closes #126

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:
- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by jmercha** [comment]
Hello @matchai! I have been able to get the prompt up and going with PowerShell on Windows, but I am having some issues getting the configuration loaded. I'm still a bit of a rust newbie, so I might need some help debugging it 😄

**Comment by khuongduybui** [comment]
Please don't give up on this guys. Please. Did I forget to say please????

**Comment by jeevcat** [comment]
What do we need to get this merged? Any idea why these tests are failing? How can I help?

**Comment by matchai** [comment]
I'm going to be closing this PR as stale.
Feel free to reopen it if you're still interested in implementing this feature, @jmercha.

**Pull request closed without merging**
