### PR TITLE
feat(fish): Enable left and right transience

### LINKED ISSUE #888: Add transient prompt configuration option
#### Is your feature request related to a problem? Please describe.
Currently, every time a command is entered, the prompt is recreated on the line below. This is normal behavior, but arguably can look cluttery when the prompt extends beyond a single line.

#### Describe the solution you'd like
The solution I propose is a configuration option for a transient prompt. The prompt would appear to stay on one line while previous commands would appear as normal. [Here's what this looks like in powerlevel10k](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif). I don't know how to implement this, nor do any particular drawbacks come to mind. Powerlevel10k's implementation could be a good place to look for inspiration.

### PR DESCRIPTION
**Pull request by rashil2000**
#### Description

Enables left and right transience for Fish shell, similar to Cmd and PowerShell

#### Motivation and Context

Closes #888

#### Screenshots (if appropriate):
image

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by davidkna — CHANGES_REQUESTED** [review]
I tried this, and it doesn't seem to trigger consistently.

**Comment by rashil2000** [comment]
Ah yes, I forgot to mention. The way `commandline --is-valid` works is it will only be true when the command is non-empty, and syntactically correct. (this is discussed in detail in https://github.com/fish-shell/fish-shell/pull/8142).

**Comment by davidkna** [comment]
@rashil2000 If this is how transience is expected to work with fish, please document the limitations.

**Comment by rashil2000** [comment]
Done

**Comment by rashil2000** [comment]
Anything left here?

**Review by davidkna — APPROVED** [review]

**Comment by davidkna** [comment]
Thanks for the contribution!

**Pull request merged**
