### PR TITLE
ci: Update CI and migrate publish job to Actions

### PR DESCRIPTION
**Pull request by matchai**
#### Description

- Replace `hecrj/setup-rust-action` with `actions-rs` tools
- Add a **Cargo Audit** test step
- Move `cargo publish` step from Azure Pipelines to GitHub Actions
	- Use `cargo-publish-all` to publish multiple packages at once
- Automate the creation of release notes

### CODE REVIEW

**Comment by johnletey** [comment]
@matchai Do you know why Clippy is complaining?

**Comment by chipbuster** [comment]
`No commit found for SHA: ` I'm guessing this is a similar issue to the one we had before where some commits just disappear from the view of GH Actions?

**Comment by matchai** [comment]
It's currently being investigated in https://github.com/actions-rs/clippy-check/issues/1

**Comment by matchai** [comment]
After successfully testing the release process in https://github.com/matchai/test-rust-actions, I can confirm that CI and releases should automate successfully. 👍

**Pull request merged**
