### PR TITLE
docs: fix typo `moudle` -> `module`

### PR DESCRIPTION
**Pull request by vladimyr**
#### Description

Fix typo in README.

#### Motivation and Context

Prior art: https://github.com/starship/starship/pull/2501#issuecomment-806214169

@erikphansen I've reused your original commit :+1: 

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by matchai — APPROVED** [review]
LGTM! 👍 
Thank you for the PR, Dario and Erik!

**Comment by vladimyr** [comment]
It is really all @erikphansen's work! 👍 Usually, I would give instructions on how to fix existing PR instead of opening a new one but Erik asked for it, and seeing one already closed (#2500) I just felt bad asking them to fight git(hub) again. 🙈 
With that being said I would very gladly share some of my git foo with you @erikphansen so you don't give up and see it through the end next time, primarily because there is really nothing to be _afraid of_ and it is actually fun. Just a few stupid chained git actions that even I managed to learn 😉

**Comment by erikphansen** [comment]
@vladimyr Thanks for handling this! The git part is easy enough I just wasn't sure what actually needed to change so things would work with the documentation translations :)

**Comment by vladimyr** [comment]
You are welcome 😊 As a rule of thumb one should newer touch anything besides English docs.

**Pull request merged**
