### PR TITLE
docs: Correct dotnet module default format to match reality

### PR DESCRIPTION
**Pull request by twpol**
#### Description
This changes the documentation's default value for the dotnet module's `format` to match what it is in the code.

#### Motivation and Context
I was customising my prompt and noticed that copying the default from the documentation did not replicate the default behaviour.

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

I have not attempted to compile the Starship application itself, but did run the development website to verify it picked up the changes using:

* Windows 10 1909
* NodeJS 12.18.4
* NPM 6.14.6
* Microsoft Edge 87.0.664.55

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

I have read the contributing document and believe I've followed everything relevant but let me know if not.

### CODE REVIEW

**Comment by chipbuster** [comment]
Hey @twpol, could you revert the changes to the translated pages? Those are managed by Crowdin, and merging any changes to them directly risks causing the Crowdin merges to conflict and fail.

The localized changes will propagate into Crowdin on their own eventually.

**Comment by twpol** [comment]
> Hey @twpol, could you revert the changes to the translated pages? Those are managed by Crowdin, and merging any changes to them directly risks causing the Crowdin merges to conflict and fail.

Sure, done.

I did try and figure out whether I should update those files or not and couldn't find anything conclusive. How do you feel about a note in `CONTRIBUTING.md` for future newbies?

**Comment by chipbuster** [comment]
> I did try and figure out whether I should update those files or not and couldn't find anything conclusive. How do you feel about a note in `CONTRIBUTING.md` for future newbies?

Yeah, I'd like that, I think. I actually went looking through that file trying to work out whether we needed to clarify those instructions. I didn't realize we hadn't put anything about the translated pages at all. Would you like to open a PR against that? If not, I can open an issue against it.

**Review by chipbuster — APPROVED** [review]

**Comment by chipbuster** [comment]
@twpol Thanks for the fix!

**Review by xEin1 — COMMENTED** [review]
.

**Pull request merged**
