### PR TITLE
feat: starship explain

### LINKED ISSUE #113: Starship Explainer
## Feature Request

I have used quite a few pre-made shell prompts in the last N years, and one thing that's always gotten to me is that it's very irritating to figure out what that weird symbol that just popped up at the edge of your prompt is. Inevitably, one of three things happens:

- I just ignore it and it never pops up again.
- It eventually pops up often enough that I open a web browser, go to the website of the prompt/google around, and eventually figure out what it is, at the cost of a 5 minute interruption to what I was doing.
- I'm mucking through the code to customize something and accidentally stumble over it.

To this day, I still don't know what all the git symbols in my ZPretzo prompt mean--I just run `git status` and worry about it there.

#### Is your feature request related to a problem? Please describe.

There ought to be an easier way to discover what all these cool glyphs mean.

#### Describe the solution you'd like

A command that can be used (maybe `starship explainer`) and it will explain what every part of the prompt means.

Pros: allows easy discovery of what each part of the prompt means.

Downsides: 
- could become very complex to build if the configuration grows too much
- would have to be maintained/changed every time the prompt is changed
- layout could be challenging.

#### Describe alternatives you've considered

Ideally you could mouse-hover over the prompt section to get a pop-up, but that depends pretty heavily on what terminal emulators are available.

It might be possible to hyperlink each part of the shell to a page that explains it, but (a) this also depends really heavily on the terminal emulator and (b) I would *definitely* click on those by accident, all the time.

### PR DESCRIPTION
**Pull request by jonstodle**
This adds the `explainer` argument to Starship which explains what the printed modules in the prompt are. It's basically implemented as suggested in [this comment](https://github.com/starship/starship/issues/113#issuecomment-521006736).

#### Description
The aforementioned issue also mentions a verbosity flag, which could explain in greater detail why the module is printed and what it's individual segments mean. This verbosity flag is not implemented.

#### Motivation and Context
This makes it possible to easily see what the different modules printed mean.
Closes #113

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?
I've tested it by running the compiled executable in a few different directories, producing different modules, and it looks to be working.

OS: macOS Catalina (10.15.1 (19B88))
Terminal: Alacritty / tmux

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by matchai** [comment]
Hey @jonstodle 👋
It looks like your PR contains the last few PRs of changes. I'd suggest rebasing over master to fix up your PR.

**Comment by jonstodle** [comment]
No problem. I think this should fix it(?)

**Comment by jonstodle** [comment]
It looks like the failing check is due to PHP?

**Comment by chipbuster** [comment]
`curl: (7) Failed to connect to secure.php.net port 443: Connection timed out`

I'm gonna guess a temporary network or server outage. Restarted the test suite...let's hope it works!

**Comment by jonstodle** [comment]
Got wrapping working, but I'm getting some weird output in zsh
Screenshot 2019-12-24 at 01 46 51

**Comment by johnletey** [comment]
> but I'm getting some weird output in zsh

@jonstodle That is weird, because in Fish (using iTerm), everything looks fine:

Shot 2019-12-24 at 19 04 29

**Comment by matchai** [comment]
I would suggest taking a look at these two fixes we have in place for ZSH printing:
https://github.com/starship/starship/blob/12e8ae85dd5661c251178947ee5d32a381edb80d/src/module.rs#L154-L157
https://github.com/starship/starship/blob/6724ce5bb5495f0a04b98abf9087cafb9866e8fe/src/modules/memory_usage.rs#L21-L26

You may need to reuse some of the logic we have in modules to make zsh behave. 😅

**Comment by johnletey** [comment]
@matchai @jonstodle I was thinking about this feature, and do you think it should be called `starship explain` or `starship explainer`? I personally like `explain` better

**Comment by jonstodle** [comment]
That was suggested in the original issue too. It might also align nicer with a possible more verbose version later: [ref](https://github.com/starship/starship/issues/113#issuecomment-521080879)

`explainer` is lifted from the initial implementation from a few months back. I'm not married to it

**Comment by chipbuster** [comment]
I think "explain"

**Comment by chipbuster** [comment]
```
> starship --help
...omitted lines...
SUBCOMMANDS:
    help      Prints this message or the help of the given subcommand(s)
    init      Prints the shell function used to execute starship
    module    Prints a specific prompt module
    prompt    Prints the full starship prompt
```

Based on our current subcommand vocabulary, it seems that `explain` would be the correct name of the subcommand.

**Comment by chipbuster** [comment]
WOOHOO!

**Pull request merged**
