### PR TITLE
docs: fix bad instructions for fish-shell

### LINKED ISSUE #251: Bad instructions for bootstrapping fish-shell
#### Current Behavior
The documentation for bootstrapping starship in fish [suggests a method](https://starship.rs/guide/#fish) which is [not supported by fish](https://github.com/fish-shell/fish-shell/issues/4951#issuecomment-385224452).

#### Expected Behavior / Possible Solution
The accepted method would be to add the following line to `config.fish`:
```fish
starship init fish | source
```

### PR DESCRIPTION
**Pull request by imbsky**
#### Description

Current instruction is wrong and it breaks a lot. The new instruction is correct for Fish and works correctly. To avoid confusing many people, the documentation should be correct. This fixes the wrong documentation.

#### Motivation and Context

Closes #251

Related issue #474

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by imbsky** [comment]
Pushed!

**Comment by imbsky** [comment]
@matchai This is an off-topic question, can I correct any mistakes or non-natural translation directly in this repository? Should I do it with Crowdin or something like that?

**Comment by matchai** [comment]
Any translation updates would best be done on Crowdin: https://translate.starship.rs

**Comment by imbsky** [comment]
Okay!

**Pull request merged**
