### PR TITLE
feat(ocaml): Add OCaml module

### LINKED ISSUE #903: Add OCaml module
#### Is your feature request related to a problem? Please describe.

There is no OCaml support yet, so adding it is a good idea.

### PR DESCRIPTION
**Pull request by matsujika**
#### Description
Added the module which displays the currently installed OCaml version.

#### Motivation and Context
Closes #903 

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Screenshots (if appropriate):
スクリーンショット 2020-05-16 4 07 31

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by vladimyr** [comment]
@matsujika Please take a look on https://github.com/matsujika/starship/pull/1 it simplifies things a bit and bring is Reason support 🎉

**Comment by vladimyr** [comment]
@matsujika Default prompt order in the docs also needs to be updated
```diff
diff --git a/docs/config/README.md b/docs/config/README.md
index 082058d..7c3ea88 100644
--- a/docs/config/README.md
+++ b/docs/config/README.md
@@ -111,6 +111,7 @@ prompt_order = [
     "java",
     "julia",
     "nodejs",
+    "ocaml",
     "php",
     "python",
     "ruby",

```

**Comment by nickwb** [comment]
Looks good. Fairly simple. Can you perhaps provide some benchmarks for us non-ocaml users? I'm not too worried about your code, but I don't know how fast `ocaml -vnum` is.

If you have `hyperfine` installed, you can do something like `hyperfine -r 100 'starship module ocaml'`

**Comment by matsujika** [comment]
@nickwb 
Here are the results I got executing from MacBook Pro 2019.
### w/o OCaml files:
Benchmark #1: ./target/release/starship module ocaml
  Time (mean ± σ):       4.6 ms ±   0.6 ms    [User: 2.3 ms, System: 1.5 ms]
  Range (min … max):     3.9 ms …   6.8 ms    100 runs

### w/ OCaml files:
Benchmark #1: ./target/release/starship module ocaml
  Time (mean ± σ):      19.6 ms ±   0.7 ms    [User: 13.2 ms, System: 4.8 ms]
  Range (min … max):    18.6 ms …  22.2 ms    100 runs

**Comment by nickwb** [comment]
> @nickwb
> Here are the results I got executing from MacBook Pro 2019.
> 
> ### w/o OCaml files:
> Benchmark #.1: ./target/release/starship module ocaml
> Time (mean ± σ): 4.6 ms ± 0.6 ms [User: 2.3 ms, System: 1.5 ms]
> Range (min … max): 3.9 ms … 6.8 ms 100 runs
> 
> ### w/ OCaml files:
> Benchmark #.1: ./target/release/starship module ocaml
> Time (mean ± σ): 19.6 ms ± 0.7 ms [User: 13.2 ms, System: 4.8 ms]
> Range (min … max): 18.6 ms … 22.2 ms 100 runs

Perfect, thank you!

**Comment by andytom** [comment]
Thank you @matsujika for the contribution and @nickwb and @vladimyr for your help reviewing the PR.

**Pull request merged**
