### PR TITLE
refactor: Move `create_fixture_repo` into common in integration tests

### PR DESCRIPTION
**Pull request by wyze**
#### Description
I moved the fixture repo creation to common since it is now used by more than one module.

#### Motivation and Context
Remove duplicated code.

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?
- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:
- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by wyze** [comment]
This might be setting the config in the wrong repo. If it fails, I think better solution would be to check for CI environment and only set the global config if running there.

**Comment by chipbuster** [comment]
Oh wow. That's definitely not part of the spec ^^

Were you running the complete integration suite (with ignored tests) outside of the container environment? We might want to consider putting a warning on that, since we're (implicitly) using `#[ignore]` as an `in-docker-only` flag at the moment.

**Comment by wyze** [comment]
Yeah, I usually just run `cargo test -- -Z unstable-options --include-ignored` locally.

**Comment by matchai** [comment]
> Yeah, I usually just run cargo test -- -Z unstable-options --include-ignored locally.

I'd suggest running `./integration_test` to run the tests in a Docker container with all our dependencies locked at fixed versions. The `ignored` tests will produce side effects and aren't meant to be run outside of Docker ([detailed here](https://github.com/starship/starship/blob/master/CONTRIBUTING.md#acceptance-testing)).

You might have ended up with a few files generated in your home directory. 😅

**Comment by wyze** [comment]
Haha, oops. Okay, I will do that in the future. I think it's still worth while to move the fixture repo creation logic to common. I can revert the checking of git config if you'd like.

**Comment by matchai** [comment]
> I think it's still worth while to move the fixture repo creation logic to common. I can revert the checking of git config if you'd like.

Sounds perfect. 👍

**Comment by matchai** [comment]
> Looks great! Out of curiosity, why is it called 'fixture'? I'm not familiar with the term.

[Test fixtures](https://en.wikipedia.org/wiki/Test_fixture#Software) are a pretty common term for pre-established static data for setting up the test context. 😄

**Pull request merged**
