### PR TITLE
docs: remove meaningless invisible character

### PR DESCRIPTION
**Pull request by KanchiShimono**
#### Description

Remove meaningless invisible character.
Browsers and some text editors do not render the git diff, but actually invisible character (U+200D: zero width joiner) was deleted.

#### Motivation and Context

Closes #

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by chipbuster** [comment]
Now that's an interesting one.

If you don't mind my asking, how did you spot this?

**Comment by chipbuster** [comment]
Ah, semantic PR bot is upset.

Could you amend your pull request to have a semantic PR message ("docs: remove meaningless invisible character" will work fine) and then force push?

**Comment by KanchiShimono** [comment]
@chipbuster 
Thank you for teaching me the way to pass semantic PR bot checking.
I amend commit message and force pushed.

> If you don't mind my asking, how did you spot this?

I use vim and it can render the invisible characters like zero width joiner.

image_vim

VSCode v1.16 or later version also become able to render.
https://code.visualstudio.com/updates/v1_63#_unicode-highlighting

image_vscode

**Review by chipbuster — APPROVED** [review]
:+1: Thanks for the catch!

**Comment by davidkna** [comment]
Thanks for spotting this @KanchiShimono, and thanks for the review @chipbuster.

**Pull request merged**
