### PR TITLE
Change gradle icon from G to 

### PR DESCRIPTION
**Pull request by koppor**
This is a (small) follow-up to https://github.com/starship/starship/pull/4423.

#### Description

This changes the gradle icon from 🅶 (NEGATIVE SQUARED LATIN CAPITAL LETTER G' (U+1F176)) to the "real" Gradle icon .

Old:

image

New:

image

#### Motivation and Context

I had major issues getting the G displayed [on my NixOS machine](https://discourse.nixos.org/t/get-all-characters-working-with-starship-in-gnome-terminal/38749?u=koppor). 

I searched the fonts on my machine, checked the Nerd fonts. Nothing worked. Then, I serached the Nerd Fonts for the gradle icon. This is different from the icon supplied.

Closes #

#### Screenshots (if appropriate):

Old:

image

New:

image

#### How Has This Been Tested?

I modified `starship.toml` to contain following configuration

```toml
[gradle]
symbol = " "
```

I carefully did a search and replace in VS.Code.  I reviewed the changes in `git gui`.

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by davidkna** [comment]
Please only add the icon for the nerd font preset and related presets. Starship is moving away from requiring nerd fonts by default.

**Comment by koppor** [comment]
The existing character did not work for me on NixOS. Even with a Nerd font.

I thought, Starship would be fully making use of Nerd Font. And then making an (instant) switch - and not a gradually one. Thus, I wanted to perfecitionize the current configuration...

**Comment by chipbuster** [comment]
@koppor Regardless of whether this change gets mainlined into the default configuration or not, we do not accept changes to the Crowdin-translated pages. Please read [CONTRIBUTING.md](https://github.com/starship/starship/blob/master/CONTRIBUTING.md#crowdin-translated-pages) for an explanation.

> I thought, Starship would be fully making use of Nerd Font.

Ultimately, we've decided that the default configuration will not use any symbols from the Unicode Private Use Areas (which includes Nerd Fonts), so Nerd Font symbols go in the presets.

**Comment by andytom** [comment]
As mentioned in the comments starship is moving aways from requiring using nerd fonts. Have closed this PR since we would not merge it.

**Pull request closed without merging**
