### PR TITLE
test: sync filesystem before each test is run

### PR DESCRIPTION
**Pull request by davidkna**
#### Description

[Apparently `.sync_all()` might not be enough to ensure new files are visible in the filesystem.](https://github.com/starship/starship/issues/886#issuecomment-667509181)
In the two test module render helpers I found, I added code to sync the filesystem before the modules are rendered. ~~This doesn't work on windows but I don't really remember the failures happening there.~~
I did five ci runs on my fork and they all worked except for unrelated failures reminiscent of #1532  

#### Motivation and Context

#886

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by davidkna** [comment]
[I added partial support for windows because the failures happen there too now.](https://github.com/starship/starship/issues/886#issuecomment-669149950)

**Comment by ATiltedTree** [comment]
After a bit of research i think it won't really help us here because were doing exactly the same as `sync_all()`:

`sync_all`'s implementation on linux

```rust
    pub fn fsync(&self) -> io::Result<()> {
        cvt_r(|| unsafe { os_fsync(self.0.raw()) })?;
        return Ok(());


        #[cfg(any(target_os = "macos", target_os = "ios"))]
        unsafe fn os_fsync(fd: c_int) -> c_int {
            libc::fcntl(fd, libc::F_FULLFSYNC)
        }
        #[cfg(not(any(target_os = "macos", target_os = "ios")))]
        unsafe fn os_fsync(fd: c_int) -> c_int {
            libc::fsync(fd)
        }
    }
```

and on windows:

```rust
pub fn fsync(&self) -> io::Result<()> {
        cvt(unsafe { c::FlushFileBuffers(self.handle.raw()) })?;
        Ok(())
    }
```

Reference:
 - [Linux](https://github.com/rust-lang/rust/blob/ec9d5241f749978150a35f82a2358f494c5b9080/library/std/src/sys/unix/fs.rs#L733-L745)
 - [Windows](https://github.com/rust-lang/rust/blob/ec9d5241f749978150a35f82a2358f494c5b9080/library/std/src/sys/windows/fs.rs#L302-L305)

It basically does exactly the same as the implementation in this PR which is also required by the man page you referenced.

> For that an explicit fsync() on a file descriptor for the directory is also needed.

While we can try it, I don't think it will help us much.
And if it does help we should just use `sync_all()` on the directory before rendering and see if that fixes it as well.

Also something I found on the man page for [sync](https://linux.die.net/man/8/sync):

> **Notes**
> On Linux, sync is only guaranteed to schedule the dirty blocks for writing; it can actually take a short time before all the blocks are finally written. 

Maybe we are still to fast for the (probably virtual) disks on github actions to sync.

**Comment by davidkna** [comment]
> After a bit of research i think it won't really help us here because were doing exactly the same as `sync_all()`:
> 
> `sync_all`'s implementation on linux
> 
> ```rust
>     pub fn fsync(&self) -> io::Result<()> {
>         cvt_r(|| unsafe { os_fsync(self.0.raw()) })?;
>         return Ok(());
> 
> 
>         #[cfg(any(target_os = "macos", target_os = "ios"))]
>         unsafe fn os_fsync(fd: c_int) -> c_int {
>             libc::fcntl(fd, libc::F_FULLFSYNC)
>         }
>         #[cfg(not(any(target_os = "macos", target_os = "ios")))]
>         unsafe fn os_fsync(fd: c_int) -> c_int {
>             libc::fsync(fd)
>         }
>     }
> ```
> 
> and on windows:
> 
> ```rust
> pub fn fsync(&self) -> io::Result<()> {
>         cvt(unsafe { c::FlushFileBuffers(self.handle.raw()) })?;
>         Ok(())
>     }
> ```
> 
> Reference:
> 
>     * [Linux](https://github.com/rust-lang/rust/blob/ec9d5241f749978150a35f82a2358f494c5b9080/library/std/src/sys/unix/fs.rs#L733-L745)
> 
>     * [Windows](https://github.com/rust-lang/rust/blob/ec9d5241f749978150a35f82a2358f494c5b9080/library/std/src/sys/windows/fs.rs#L302-L305)
> 
> 
> It basically does exactly the same as the implementation in this PR which is also required by the man page you referenced.
> 
> > For that an explicit fsync() on a file descriptor for the directory is also needed.
> 
> While we can try it, I don't think it will help us much.
> And if it does help we should just use `sync_all()` on the directory before rendering and see if that fixes it as well.

It's true that the implementation here is more or less identical to the one in rust stdlib but as far as I can tell it's not possible to `sync_all` directories with the rust stdlib. (Permission error on windows and EISDIR on linux)

**Comment by davidkna** [comment]
I think I made it work with `sync_all`. Hopefully this works on macos too.

**Comment by davidkna** [comment]
looks like this doesn't work

**Pull request closed without merging**
