### PR TITLE
feat(env_var): Add support for env_var.VAR in format

### LINKED ISSUE #3259: Customize env_var display order in format like what can be done for custom
#### Is your feature request related to a problem? Please describe.
Can't reorder multiple `env_var` sections individually using `format`.

#### Describe the solution you'd like
I want to be able to reorder `env_var` the same as you can reorder custom sections by including `${custom.section}` in the `format`.

e.g.
```toml
format = "${env_var.WSL_DISTRO_NAME}$all"

[env_var.WSL_DISTRO_NAME]
format = "[$env_value]($style) in "
style = "bold dimmed green"
```

#### Describe alternatives you've considered
Using `custom` instead of `env_var`.

### PR DESCRIPTION
**Pull request by davidkna**
#### Description

This PR allows using `${env_var.VAR}` in format strings. Unlike #3375, I handled this in a shared manner with custom modules by moving the code paths for custom and `env_var` modules closer to other regular modules, leveraging `modules::handle` (which tests for custom modules were using). This allows removing the timing-handling from the custom module code.

#### Motivation and Context

Closes #3259
Closes #3375

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Review by andytom — APPROVED** [review]
LGTM but looks like we have some merge conflicts.

**Comment by jaimehrubiks** [comment]
for some reason I cannot make this work

```
right_format = """>${env_var.ZVM_MODE_CUSTOM}<"""
[env_var.ZVM_MODE_CUSTOM]
variable = 'ZVM_MODE_CUSTOM'
default = ''
```

**Comment by davidkna** [comment]
@jaimehrubiks These changes aren't included in the latest version of starship yet. They will be included with starship 1.13.

**Comment by jaimehrubiks** [comment]
Ups, now I see! Thank you!

**Pull request merged**
