### PR TITLE
feat: Add migration script for format strings

### PR DESCRIPTION
**Pull request by heyrict**
#### Description
This adds a binary `starship_migrate_0_40` that updates the config file.

Changes proposed in #1056 are applied.

#### Motivation and Context

See https://github.com/starship/starship/issues/1057#issuecomment-611582686

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by heyrict** [comment]
I'm wondering if this PR should be included in the repo `starship/starship` or in separate repo. Actually it is a onetime-off script and won't need to be compiled every time with `starship` after v0.40. It seems cleaner if we put it in a separate repo, but it will force developers to open two PRs to refactor a module, one to `starship/starship`, and another to the migration script.

I'm thinking about adding the migration binary here and move the code to another repo when all modules get refactored. Any thoughts @matchai ?

**Comment by nickwb** [comment]
Are we going to force users to run this script manually? I think that would be a unfortunate outcome..

An alternative solution might look like this:

1. `config_schema = n` becomes a part of the root config. (where `n` is a number). If the property is missing, then we assume `n = 1` (i.e., all current config files are schema version 1).
2. When loading the config during a normal `starship prompt`, "hot migrate" any config from the old version to the latest version, using as many migration steps as is necessary. 
3. Write a warning out to stderr whenever we needed to migrate prior to drawing the prompt: `"Your starship configuration is using an outdated format. Run 'starship config migrate' to update it."`

**Comment by heyrict** [comment]
@nickwb Thanks for your comments. I agree with you in point 1 and 3. I don't think 2 works good as it will change the format (probably deleting all comments) of the config file without users' confirmation.

This PR is not included in the umbrella issue. I think it is safe to be closed as per discussion in https://github.com/starship/starship/discussions/1116#discussioncomment-6579-permalink . Most modules will work the same as before with the config examples in `docs/config/README.md` except a few (`character`, `memory` and `time` afaik).

**Comment by andytom** [comment]
I have created two issues for the points that have been raised here.

**Pull request closed without merging**
