### PR TITLE
feat(spotify): start

### PR DESCRIPTION
**Pull request by Milo123459**
#### Description

This adds a spotify module.
#### Motivation and Context

Closes #

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

This PR is a draft as I'm working on it actively and currently doesn't work. It can get values, but refuses to render them. Please help if you know the issue. Much appreciated.

### CODE REVIEW

**Comment by Milo123459** [comment]
Windows support is coming along nicely and should (hopefully) be done by the end of the week. Wish me luck!

**Comment by Milo123459** [comment]
I'll get this working eventually. Sorry for not working on it recently.

**Comment by matchai** [comment]
Closing this PR for now as it has been a draft for a couple of months now.
Please feel free to reopen it when the PR is ready to be reviewed.

**Comment by mars-s** [comment]
was this implemented? or dropped?

**Pull request closed without merging**
