### PR TITLE
refactor(git_commit): Stop using libgit2

### PR DESCRIPTION
**Pull request by andytom**
#### Description

This switches the git_commit module from using libgit2 to shelling out
to git. This removes the dependency on libgit2 and should solve some
edge cases where libgit2 doesn't respond the same way that git does.

#### Motivation and Context

Closes #

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by matchai** [comment]
Trying it out locally, it seems like this change seriously affects the `git_commit` module's performance.
What would usually take 1ms now takes >40ms on average. Even non-git repos hover around 30ms for me, making it the slowest module at times.

**Comment by andytom** [comment]
> Trying it out locally, it seems like this change seriously affects the `git_commit` module's performance.
> What would usually take 1ms now takes >40ms on average. Even non-git repos hover around 30ms for me, making it the slowest module at times.

Hmmm, that is strange for me at least it is a wee bit slower (around 6.0ms compared to 2.6ms) but never that slow.

```
❯ hyperfine 'target/release/starship module git_commit' 'starship module git_commit'
Benchmark #1: target/release/starship module git_commit
  Time (mean ± σ):       6.0 ms ±   0.8 ms    [User: 2.4 ms, System: 5.0 ms]
  Range (min … max):     4.6 ms …  12.2 ms    222 runs
 
  Warning: Command took less than 5 ms to complete. Results might be inaccurate.
 
Benchmark #2: starship module git_commit
  Time (mean ± σ):       2.6 ms ±   0.6 ms    [User: 1.2 ms, System: 1.9 ms]
  Range (min … max):     1.7 ms …   5.1 ms    607 runs
 
  Warning: Command took less than 5 ms to complete. Results might be inaccurate.
 
Summary
  'starship module git_commit' ran
    2.37 ± 0.63 times faster than 'target/release/starship module git_commit'

```

**Comment by davidkna** [comment]
macOS seemed fine, but on Windows it was 4 times slower for me with this PR.

Git repo:
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `~\.cargo\bin\starship.exe module git_commit` | 27.9 ± 2.2 | 24.9 | 38.7 | 1.00 |
| `.\target\release\starship.exe module git_commit` | 110.3 ± 4.0 | 103.6 | 121.0 | 3.96 ± 0.34 |

No git repo:
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `~\.cargo\bin\starship.exe module git_commit` | 21.1 ± 1.5 | 18.2 | 25.7 | 1.00 |
| `.\starship\target\release\starship.exe module git_commit` | 80.9 ± 2.0 | 75.8 | 84.1 | 3.84 ± 0.29 |

**Comment by andytom** [comment]
I'm going to convert this back to draft and see if I can figure out a way to make this behave better on Windows and macOS. If anyone else has some suggestions please add a comment.

**Pull request closed without merging**
