### PR TITLE
docs(i18n): Fix French typo

### PR DESCRIPTION
**Pull request by VincentHardouin**
#### Description
I fixed some French typo and mistakes.

#### Motivation and Context
Improve French documentation.

### CODE REVIEW

**Comment by mickimnet** [comment]
Hello @VincentHardouin,

thank you very, very much for your update on the French translation of the readme and the advanced configuration for the website.

All translations for the website are done through the system [Crowdin](https://translate.starship.rs/), which will be automatically generated and included in the language sections.

Could you be please so kind and change/suggest the changes at [Crowdin](https://translate.starship.rs/)?

Thanks a lot and take care!

**Comment by chipbuster** [comment]
I'd love to merge this, but it'll create merge conflicts with our Crowdin bot further down the line. We'd love to have your contributions over at Crowdin as @mickimnet said!

**Comment by VincentHardouin** [comment]
Hi ! 

I have done it in Crowdin !

**Comment by mickimnet** [comment]
@VincentHardouin thank you so much!

**Pull request closed without merging**
