### PR TITLE
feat(modules): add vim_shell module

### LINKED ISSUE #5569: Add support for vim_shell
just as the title, please add the support for vim's embed shell. This can be done by detact the env var `$VIMRUNTIME` 

I can do it by a custom component, but if support is builtin, it should be better.

Here is my custom component here:

```toml
[custom.vim_shell]
format = "[](fg:#7a7a7a bg:#444444)[ $symbol ]($style)"
style = "fg:#7a7a7a bg:#444444"
symbol = "[](fg:green bg:#444444)"
when = "test \"$VIMRUNTIME\" != \"\""
```

### PR DESCRIPTION
**Pull request by cathaysia**
in vim, show a icon like this:
close #5569 
image

### CODE REVIEW

**Comment by mickimnet** [comment]
Do you plan to add documentation for the new module?

**Comment by cathaysia** [comment]
if prs are always welcome, I'll add documentation and tests for it if needed.
________________________________

**Comment by cathaysia** [comment]
this should completed.

**Comment by mickimnet** [comment]
I just realized that you changed the pull request to also include a `[direnv]` module. There is already a open pull request for that—see: #5157 

Also, this would close #5569

**Comment by cathaysia** [comment]
sorry, i'm forget there is a direnv module pr already. I remove direnv module and revert the changes about docs(it's because tailwindcss lsp format the markdown.).

**Pull request closed without merging**
