### PR TITLE
chore(github-actions): Remove AUR deploy

### PR DESCRIPTION
**Pull request by ATiltedTree**
#### Description

The AUR package was adopted as a community package so we don't need to run the AUR deploy action anymore:
https://archlinux.org/packages/community/x86_64/starship/

Also some small YAML formatting changes.

#### Motivation and Context

I just saw it was adopted so I created this PR

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by chipbuster** [comment]
I guess this is the best place to have this discussion: should we also remove `starship-bin` in that case? I doubly don't see the point of that on Arch now, since you can get pretty much the exact same product via the official repos.

Also, do you know what the standard procedure is for providing an AUR package that shadows the official repo, but is available on multiple architectures?

**Comment by ATiltedTree** [comment]
Going after the [wiki](https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Rules_of_submission), there shouldn't be any AUR package shadowing repo packages. And since `starship` [is already packaged in Archlinux ARM](https://archlinuxarm.org/packages?q=starship), I don't think that there is a need for a `-bin` package, since that are all the architectures we support anyways.

**Comment by chipbuster** [comment]
I think I got a request for PPC support at some point...regardless, I think `starship-git` (which is not under my control) should be enough for anyone who really needs to build from source.

**Review by chipbuster — APPROVED** [review]
:+1:

**Pull request merged**
