### PR TITLE
Fixed Winget Installation Error

### PR DESCRIPTION
**Pull request by Esai-Keshav**
The Winget installation command is missing the source flag I have added that 

#### Description
The installation command is causing the error
`winget install --id Starship.Starship`

```cmd

C:\Users\user>winget install --id Starship.Starship
Failed when searching source: msstore
An unexpected error occurred while executing the command:
WinHttpSendRequest: 12030: The connection with the server was terminated abnormally


The following packages were found among the working sources.
Please specify one of them using the --source option to proceed.
Name     Id                Source
---------------------------------
starship Starship.Starship winget

```

#### Motivation and Context
When I tried to install using the winget command it caused source not defined error. If the source is defined it will easy for installation. 

#### How Has This Been Tested?

- [x] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by davidkna** [comment]
Did you run some sort of utility to slim down Windows that could have uninstalled the MS store?

**Comment by Esai-Keshav** [comment]
The installation the source is `winget` not Ms store

**Comment by davidkna** [comment]
It just seems that rather than a general issue, this could be caused by issues with your system's configuration (even if winget is perhaps acting overzealously here).

**Comment by Esai-Keshav** [comment]
> It just seems that rather than a general issue, this could be caused by issues with your system's configuration (even if winget is perhaps acting overzealously here).

While installing using winget it is compulsory to define the source in the new update of winget

**Comment by davidkna** [comment]
There does not seem to be the case on my system, both with the current stable and preview releases. I assume there is some issue around the Window Store on your system.

**Pull request closed without merging**
