### PR TITLE
docs(preset): add Hide Runtime Versions preset

### LINKED ISSUE #2779: Disable all "version of X" packages
#### Is your feature request related to a problem? Please describe.

I’d like to disable all plugin that shows the version of the software related to the project in the current folder. 

Most of the development I’m doing happen in Docker, so the host version is often irrelevant. I can manually disable those package, but it would be handy to be able to disable every one of them at once

#### Describe the solution you'd like

The default is `format = "$all"` maybe another shortcut for `$all but $versions` could be added?

#### Describe alternatives you've considered

At the moment I disable the packages as I stumble upon them while changing directory. It’s not that tedious, but it would ve lovely to change a setting and be done

### PR DESCRIPTION
**Pull request by kidonng**
#### Description

Add a "Hide Runtime Versions" preset to hides the version of language runtimes.

#### Motivation and Context

Closes #2779

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by Milo123459** [comment]
I think this would be best if there was some kind of, script, that automatically regenerated docs to do this? Like, a script that gets all modules, and then combines it all to the section on the docs?

**Comment by kidonng** [comment]
You are welcome to write a script to generate the presets automatically and submit a separate PR.

**Comment by Milo123459** [comment]
Will do

**Comment by andytom** [comment]
Thank you for your contribution @kidonng

**Pull request merged**
