### PR TITLE
refactor(dotnet): ".NET" instead of "•NET"

### PR DESCRIPTION
**Pull request by eyalch**
"•NET" looks quite weird, especially since the official writing is ".NET".

#### Description
The official writing is ".NET" ([source](https://dotnet.microsoft.com/)), so why not use it?

#### Motivation and Context
It doesn't really solve anything, it just bugged me a little, but then again, it's just my opinion.
Closes #2423 

#### How Has This Been Tested?
No testing was required, since I just used a simple search-and-replace.

#### Checklist:
- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by vladimyr** [comment]
@eyalch Please don't change dotnet writing style inside translated docs because it creates issues with Crowdin automated translation: https://github.com/starship/starship/pull/2447#pullrequestreview-610979000

**Comment by eyalch** [comment]
@vladimyr Got it. So which files should I have changed? Only these?
- `docs/config/README.md`
- `src/configs/dotnet.rs`
- `src/modules/dotnet.rs`

**Comment by vladimyr** [comment]
That's right. 👍

**Comment by eyalch** [comment]
Done!

**Review by vladimyr — APPROVED** [review]
LGTM 👍

**Comment by andytom** [comment]
Thank you for your contribution @eyalch and thank you for reviewing @vladimyr.

**Pull request merged**
