### PR TITLE
feat: Add xonsh support

### LINKED ISSUE #272: Support for the xonsh shell
If it is possible to combine starship with the Python-based shell [xonsh](https://xon.sh/tutorial.html), I think the result would be awesome.

### PR DESCRIPTION
**Pull request by vladimyr**
#### Description
Adds `xonsh` init script.

#### Motivation and Context

Closes #272 

#### Screenshots (if appropriate):
image

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by vladimyr** [comment]
> The PR looks great to me! Thank you for taking the time to add docs everywhere they're needed. 😄

I'm giving my best 😁 

> I have installed xonsh directly from Brew (xonsh/0.9.18) if that's of any help.

Well, we took different routes. I've installed it using [`pipx`](https://pipxproject.github.io/pipx/). I'll try with Homebrew and let you know.

> If you'd prefer more synchronous communication while troubleshooting, I'm always available on the project Discord: [discord.gg/8Jzqu3T](https://discord.gg/8Jzqu3T)

Sure, I'll join 👍

**Comment by vladimyr** [comment]
Well, this reached a dead end 😞 

The main difference between Homebrew and pip/x install of xonsh is that Homebrew installs optional prompt-toolkit too. Without it, xonsh simply uses readline and works fine with ANSI escape sequences. With prompt-toolkit in use, things go wrong https://github.com/xonsh/xonsh/issues/1403 so even if I figure out import error there is still a bigger wall to hit. With that being said and because I'm not a python expert and don't have enough time/knowledge to dive deep into xonsh/ptk internals I think it is fair to give up here. I'm sorry, I hope I put up a good fight ⚔️

**Comment by anki-code** [comment]
### I've ported starship as [xontrib-prompt-starship](https://github.com/anki-code/xontrib-prompt-starship)

**Comment by vladimyr** [comment]
> The main difference between Homebrew and pip/x install of xonsh is that Homebrew installs optional prompt-toolkit too. Without it, xonsh simply uses readline and works fine with ANSI escape sequences. With prompt-toolkit in use, things go wrong [xonsh/xonsh#1403](https://github.com/xonsh/xonsh/issues/1403)

This is not true anymore. Xonsh now properly supports escape sequences with `prompt-toolkit` being used as demonstrated here: https://github.com/starship/starship/issues/272#issuecomment-792642151

Kudos to @anki-code for following xonsh/xonsh#1403 and bringing this to my attention :+1: 

Thus restarting this effort...

**Comment by djmattyg007** [comment]
What would it take to get this PR merged? :pray:

**Comment by jeremyschlatter** [comment]
I fixed the merge conflicts and the [NameError](https://github.com/starship/starship/pull/1265#pullrequestreview-420227964) in a new PR: https://github.com/starship/starship/pull/2807

**Pull request closed without merging**
