### PR TITLE
refactor(git_commit): small refactor 

### PR DESCRIPTION
**Pull request by cymruu**
#### Description
Removed unnecessarily duplicated piece of code

#### Motivation and Context
👀 🤔 💡 

#### How Has This Been Tested?
- [x] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by andytom** [comment]
I believe the test failures here are caused by an outdated dependency that has since been updated if you rebase this it should pass the tests.

**Comment by cymruu** [comment]
@andytom bump, semantic PR fails for some reason :/

**Comment by Milo123459** [comment]
Add another commit. To fix:
`git commit -m "Fix"`
`git push --force`

**Review by andytom — APPROVED** [review]

**Comment by andytom** [comment]
Thank you for your contribution @cymruu

**Pull request merged**
