### PR TITLE
feat(directory): Add home directory symbol

### LINKED ISSUE #1174: Allow us to modify home directory symbol (~) in [directory] options
Please give us a possibility to replace the default symbol for the **home directory** _(tilde character)_ **'~'** to any other symbol, such as home emoticon -🏠.

Add an option under the **[directory]** settings in configuration file ```starship.toml``` _(default)_:
```
[directory]
home_directory_symbol = "🏠"
```

Which should give us an excepted result like this:
```
via USER at HOSTNAME in 📂: 🏠/Projects/ExampleDirectory
```

**Why?**
I strongly believe the main benefit of a Starship is to be highly customizable. Some people, like me, love to add more icons. 😉

### PR DESCRIPTION
**Pull request by toti1212**
#### Description

As another prompt libraries, could be good if we can modify and/or add a symbol when the current directoy is home (~). I added the option to enable/disable the symbol (`show_home_symbol`) and also an option to customize it (`home_symbol`), 🏠   by default 

Fixes #1174

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by mickimnet** [comment]
Did you take a look at #1209, which was based of #1174 ?

**Comment by toti1212** [comment]
Sorry, but I hadn't seen #1209  😔 . This approach is simpler and doesn't take subdirectories into account, only the ~ directory. But, since there is some work in progress, feel free to close this RP if you want and we can continue to contribute on the other two.

**Review by andytom — COMMENTED** [review]
I think there might be a simpler way to implement this. We currently have [`HOME_SYMBOL`](https://github.com/starship/starship/blob/master/src/modules/directory.rs#L19) defined as a constant, I think if you just make that configurable with the default being `~` and it would be enough to resolve this.

**Comment by toti1212** [comment]
You are right @andytom . I took your comments into account and I updated the solution. But, as I said, if this PR looks good, welcome! But if not, let's continue with the other two! 🙂

**Review by andytom — APPROVED** [review]
LGTM.

**Comment by andytom** [comment]
Thank you for your contribution @toti1212

**Comment by toti1212** [comment]
You are welcome! Keep it up guys!

**Pull request merged**
