### PR TITLE
chore: filter crate/s contents

### PR DESCRIPTION
**Pull request by vladimyr**
#### Description

Filter out unnecessary crate contents.

#### Motivation and Context

Currently published (`v0.51.0`) [crate](https://static.crates.io/crates/starship/starship-0.51.0.crate) contains ~a lot of~ some unnecessary stuff.

<details>
<summary>Complete <code>starship-0.51.0.crate</code> contents listing</summary>

```
starship-0.51.0/.cargo/audit.toml
starship-0.51.0/.cargo_vcs_info.json
starship-0.51.0/.github/FUNDING.yml
starship-0.51.0/.github/ISSUE_TEMPLATE/Bug_report.md
starship-0.51.0/.github/ISSUE_TEMPLATE/Feature_request.md
starship-0.51.0/.github/ISSUE_TEMPLATE/config.yml
starship-0.51.0/.github/PULL_REQUEST_TEMPLATE.md
starship-0.51.0/.github/chglog/CHANGELOG.tpl.md
starship-0.51.0/.github/chglog/RELEASE.tpl.md
starship-0.51.0/.github/chglog/changelog.yml
starship-0.51.0/.github/chglog/release.yml
starship-0.51.0/.github/workflows/deploy.yml
starship-0.51.0/.github/workflows/security_audit.yml
starship-0.51.0/.github/workflows/workflow.yml
starship-0.51.0/.gitignore
starship-0.51.0/.rustfmt.toml
starship-0.51.0/CODE_OF_CONDUCT.md
starship-0.51.0/CONTRIBUTING.md
starship-0.51.0/Cargo.lock
starship-0.51.0/Cargo.toml
starship-0.51.0/Cargo.toml.orig
starship-0.51.0/Cross.toml
starship-0.51.0/LICENSE
starship-0.51.0/README.md
starship-0.51.0/build.rs
starship-0.51.0/crowdin.yml
starship-0.51.0/install/install.sh
starship-0.51.0/snapcraft.yaml
starship-0.51.0/src/bug_report.rs
starship-0.51.0/src/config.rs
starship-0.51.0/src/configs/aws.rs
starship-0.51.0/src/configs/battery.rs
starship-0.51.0/src/configs/character.rs
starship-0.51.0/src/configs/cmake.rs
starship-0.51.0/src/configs/cmd_duration.rs
starship-0.51.0/src/configs/conda.rs
starship-0.51.0/src/configs/crystal.rs
starship-0.51.0/src/configs/custom.rs
starship-0.51.0/src/configs/dart.rs
starship-0.51.0/src/configs/directory.rs
starship-0.51.0/src/configs/docker_context.rs
starship-0.51.0/src/configs/dotnet.rs
starship-0.51.0/src/configs/elixir.rs
starship-0.51.0/src/configs/elm.rs
starship-0.51.0/src/configs/env_var.rs
starship-0.51.0/src/configs/erlang.rs
starship-0.51.0/src/configs/gcloud.rs
starship-0.51.0/src/configs/git_branch.rs
starship-0.51.0/src/configs/git_commit.rs
starship-0.51.0/src/configs/git_state.rs
starship-0.51.0/src/configs/git_status.rs
starship-0.51.0/src/configs/go.rs
starship-0.51.0/src/configs/helm.rs
starship-0.51.0/src/configs/hg_branch.rs
starship-0.51.0/src/configs/hostname.rs
starship-0.51.0/src/configs/java.rs
starship-0.51.0/src/configs/jobs.rs
starship-0.51.0/src/configs/julia.rs
starship-0.51.0/src/configs/kotlin.rs
starship-0.51.0/src/configs/kubernetes.rs
starship-0.51.0/src/configs/lua.rs
starship-0.51.0/src/configs/memory_usage.rs
starship-0.51.0/src/configs/mod.rs
starship-0.51.0/src/configs/nim.rs
starship-0.51.0/src/configs/nix_shell.rs
starship-0.51.0/src/configs/nodejs.rs
starship-0.51.0/src/configs/ocaml.rs
starship-0.51.0/src/configs/openstack.rs
starship-0.51.0/src/configs/package.rs
starship-0.51.0/src/configs/perl.rs
starship-0.51.0/src/configs/php.rs
starship-0.51.0/src/configs/purescript.rs
starship-0.51.0/src/configs/python.rs
starship-0.51.0/src/configs/ruby.rs
starship-0.51.0/src/configs/rust.rs
starship-0.51.0/src/configs/scala.rs
starship-0.51.0/src/configs/shell.rs
starship-0.51.0/src/configs/shlvl.rs
starship-0.51.0/src/configs/singularity.rs
starship-0.51.0/src/configs/starship_root.rs
starship-0.51.0/src/configs/status.rs
starship-0.51.0/src/configs/swift.rs
starship-0.51.0/src/configs/terraform.rs
starship-0.51.0/src/configs/time.rs
starship-0.51.0/src/configs/username.rs
starship-0.51.0/src/configs/vagrant.rs
starship-0.51.0/src/configs/zig.rs
starship-0.51.0/src/configure.rs
starship-0.51.0/src/context.rs
starship-0.51.0/src/formatter/mod.rs
starship-0.51.0/src/formatter/model.rs
starship-0.51.0/src/formatter/parser.rs
starship-0.51.0/src/formatter/spec.pest
starship-0.51.0/src/formatter/string_formatter.rs
starship-0.51.0/src/init/mod.rs
starship-0.51.0/src/init/starship.bash
starship-0.51.0/src/init/starship.elv
starship-0.51.0/src/init/starship.fish
starship-0.51.0/src/init/starship.ion
starship-0.51.0/src/init/starship.ps1
starship-0.51.0/src/init/starship.tcsh
starship-0.51.0/src/init/starship.zsh
starship-0.51.0/src/lib.rs
starship-0.51.0/src/logger.rs
starship-0.51.0/src/main.rs
starship-0.51.0/src/module.rs
starship-0.51.0/src/modules/aws.rs
starship-0.51.0/src/modules/battery.rs
starship-0.51.0/src/modules/character.rs
starship-0.51.0/src/modules/cmake.rs
starship-0.51.0/src/modules/cmd_duration.rs
starship-0.51.0/src/modules/conda.rs
starship-0.51.0/src/modules/crystal.rs
starship-0.51.0/src/modules/custom.rs
starship-0.51.0/src/modules/dart.rs
starship-0.51.0/src/modules/directory.rs
starship-0.51.0/src/modules/docker_context.rs
starship-0.51.0/src/modules/dotnet.rs
starship-0.51.0/src/modules/elixir.rs
starship-0.51.0/src/modules/elm.rs
starship-0.51.0/src/modules/env_var.rs
starship-0.51.0/src/modules/erlang.rs
starship-0.51.0/src/modules/gcloud.rs
starship-0.51.0/src/modules/git_branch.rs
starship-0.51.0/src/modules/git_commit.rs
starship-0.51.0/src/modules/git_state.rs
starship-0.51.0/src/modules/git_status.rs
starship-0.51.0/src/modules/golang.rs
starship-0.51.0/src/modules/helm.rs
starship-0.51.0/src/modules/hg_branch.rs
starship-0.51.0/src/modules/hostname.rs
starship-0.51.0/src/modules/java.rs
starship-0.51.0/src/modules/jobs.rs
starship-0.51.0/src/modules/julia.rs
starship-0.51.0/src/modules/kotlin.rs
starship-0.51.0/src/modules/kubernetes.rs
starship-0.51.0/src/modules/line_break.rs
starship-0.51.0/src/modules/lua.rs
starship-0.51.0/src/modules/memory_usage.rs
starship-0.51.0/src/modules/mod.rs
starship-0.51.0/src/modules/nim.rs
starship-0.51.0/src/modules/nix_shell.rs
starship-0.51.0/src/modules/nodejs.rs
starship-0.51.0/src/modules/ocaml.rs
starship-0.51.0/src/modules/openstack.rs
starship-0.51.0/src/modules/package.rs
starship-0.51.0/src/modules/perl.rs
starship-0.51.0/src/modules/php.rs
starship-0.51.0/src/modules/purescript.rs
starship-0.51.0/src/modules/python.rs
starship-0.51.0/src/modules/ruby.rs
starship-0.51.0/src/modules/rust.rs
starship-0.51.0/src/modules/scala.rs
starship-0.51.0/src/modules/shell.rs
starship-0.51.0/src/modules/shlvl.rs
starship-0.51.0/src/modules/singularity.rs
starship-0.51.0/src/modules/status.rs
starship-0.51.0/src/modules/swift.rs
starship-0.51.0/src/modules/terraform.rs
starship-0.51.0/src/modules/time.rs
starship-0.51.0/src/modules/username.rs
starship-0.51.0/src/modules/utils/directory.rs
starship-0.51.0/src/modules/utils/directory_nix.rs
starship-0.51.0/src/modules/utils/directory_win.rs
starship-0.51.0/src/modules/utils/mod.rs
starship-0.51.0/src/modules/utils/path.rs
starship-0.51.0/src/modules/vagrant.rs
starship-0.51.0/src/modules/zig.rs
starship-0.51.0/src/print.rs
starship-0.51.0/src/segment.rs
starship-0.51.0/src/test/fixtures/git-repo.bundle
starship-0.51.0/src/test/fixtures/hg-repo.bundle
starship-0.51.0/src/test/mod.rs
starship-0.51.0/src/utils.rs
```
</details>

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux** _(Tested using `cargo package --list`)_
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by vladimyr** [comment]
For sake of convenience here is diff between old and new listing:
```diff
--- crate-listing.old	2021-03-24 05:58:26.863733738 +0000
+++ crate-listing.new	2021-03-24 05:57:16.887499502 +0000
@@ -1,21 +1,4 @@
-.cargo/audit.toml
 .cargo_vcs_info.json
-.github/FUNDING.yml
-.github/ISSUE_TEMPLATE/Bug_report.md
-.github/ISSUE_TEMPLATE/Feature_request.md
-.github/ISSUE_TEMPLATE/config.yml
-.github/PULL_REQUEST_TEMPLATE.md
-.github/chglog/CHANGELOG.tpl.md
-.github/chglog/RELEASE.tpl.md
-.github/chglog/changelog.yml
-.github/chglog/release.yml
-.github/workflows/deploy.yml
-.github/workflows/security_audit.yml
-.github/workflows/workflow.yml
-.gitignore
-.rustfmt.toml
-CODE_OF_CONDUCT.md
-CONTRIBUTING.md
 Cargo.lock
 Cargo.toml
 Cargo.toml.orig
@@ -23,9 +6,6 @@
 LICENSE
 README.md
 build.rs
-crowdin.yml
-install/install.sh
-snapcraft.yaml
 src/bug_report.rs
 src/config.rs
 src/configs/aws.rs
 
```

**Review by andytom — COMMENTED** [review]
Is it worth also including the contents of `.cargo/` and `.rustfmt.toml`?

**Comment by vladimyr** [comment]
That's an interesting question. I've included only what is absolutely necessary to (cross-)compile it. I'd argue that rustfmt and audit stuff falls in the same bucket as tests. They are useful in development setup but not really necessary for producing the working build?

**Comment by vladimyr** [comment]
And we just got rid of that `.cargo/audit.toml` file by means of #2536 :tada:

**Comment by vladimyr** [comment]
The motivation for proposed changes is to make an installation from the source as fast and efficient as possible.
Optimizing for the following use case:
```sh
cargo install --locked starship
```

**Review by andytom — APPROVED** [review]

**Comment by andytom** [comment]
Thanks for cleaning this up @vladimyr

**Pull request merged**
