### PR TITLE
docs: Add link to `fish-async-prompt` plugin

### PR DESCRIPTION
**Pull request by andreiborisov**
#### Description
Add instructions on how to run Starship asynchronously in fish.

#### Motivation and Context
There is an excellent plugin for fish shell: [fish-async-prompt](https://github.com/acomagu/fish-async-prompt), which allows to run any prompt asynchronously and is extremely useful for Starship. I'm personally using this combination for quite some time and it's a match made in heaven.

This simple PR adds a link to the plugin, so Starship fish users would be aware of its existence and a way to use Starship without prompt slowdown which can be significant.

### CODE REVIEW

**Comment by mickimnet** [comment]
Hello @andreiborisov,

Thank you for your contribution. What is the benefit of using a plugin for _Fish Shell_, that does add more functions, before `Starship` is executed, especially because `Starship` has builtin multithreading?

Thanks and take care
Mick

PS: on a side note, all translations for the website are done through the system [Crowdin](https://translate.starship.rs/), which will be automatically generated and included in the language sections.

**Comment by andreiborisov** [comment]
> Thank you for your contribution. What is the benefit of using a plugin for _Fish Shell_, that does add more functions, before `Starship` is executed, especially because `Starship` has builtin multithreading?

Without this plugin, you need to wait before Starship completes execution to use the terminal, which for some repos/folders can take seconds. With this plugin, you can type your next command, *while* Starship is working on printing the prompt, so jumping between folders is instantaneous.

> PS: on a side note, all translations for the website are done through the system Crowdin, which will be automatically generated and included in the language sections.

Thanks, I wasn't aware of that, I'll update my PR shortly.

**Comment by mickimnet** [comment]
@andreiborisov thanks for the show case. We‘re normally very shell agnostic and tend to not support specific shell configurations. Let me check it out myself in the next couple of days and think about how to include it.

**Comment by andreiborisov** [comment]
Thanks! Looking forward to your evaluation.

**Comment by chipbuster** [comment]
@mickimnet @andreiborisov We now have the "Advanced Installation" page, which offers a potential alternate location for this.

The real question, in my mind, is where this information should go. If we added every little tip and trick into the official documentation, it could be a candidate for a small GitBook. So should this go in official docs? Strictly speaking, it's not an installation technique. Is there some community location (here on GH) where it could go?

**Comment by mickimnet** [comment]
**First**: I finally installed the [fish-async-prompt](https://github.com/acomagu/fish-async-prompt), but I'm not done with testing it. I've some weird things on my Ubuntu machine, but that could be related to being _my Ubuntu_ machine 🤪. Please give me a couple of more days to test it.

**Second**, to @chipbuster question about the location: 
> The real question, in my mind, is where this information should go.

What about putting it in the `Advanced Configuration` section? In my opinion it is more related to _configuration_ as it is to _installation_. What do you think?

**Comment by andreiborisov** [comment]
I would say `Advanced Installation` page suits it better since this is about how Starship integrates with the shell, `Advanced Configuration` in my mind is more about configuring the prompt itself.

**Comment by mickimnet** [comment]
Yeah, it‘s a bit of an edge case. On one side, it is related how to integrate _Starship_ with your shell and on the other side, it is directly related to the prompt (configuration).

In order to get out of the edge case: where would you put information about how to get a `Right Prompt` with _Starship_: configuration or installation?

**Comment by chipbuster** [comment]
> In order to get out of the edge case: where would you put information about how to get a `Right Prompt` with _Starship_: configuration or installation?

I have a personal answer to this, but I'm curious to know what Andrei thinks.
 
> PS: Now, I kind of get where Chipbuster‘s question regarding GitHub came from. Maybe, we use the Wiki-Feature here in GitHub for „Tips & Tricks“? Or make a „Tips & Tricks“ section in [Discussions](https://github.com/starship/starship/discussions)?

matchai has expressed preference for not using the wiki feature because it's easy for it to get desynced (if it was possible to update the wiki via commits/PRs like on GitLab, perhaps this wouldn't be as bad). I do think a community tips and trick section would be nice, but our main website is already pretty full (and going to bloat up a little more over this next year as the "Advanced Installation" section fills up), and I feel like community discussions here on GH don't quite get as many eyes as I feel like some of the posts should have.

**Comment by andreiborisov** [comment]
> In order to get out of the edge case: where would you put information about how to get a `Right Prompt` with Starship: configuration or installation?

> I have a personal answer to this, but I'm curious to know what Andrei thinks.

I'd say configuration. At least I would search it in the configuration section first if I'd be a new Starship user.

**Comment by mickimnet** [comment]
> > In order to get out of the edge case: where would you put information about how to get a `Right Prompt` with Starship: configuration or installation?
> 
> I'd say configuration. At least I would search it in the configuration section first if I'd be a new Starship user.

Thank you for your view. That opened a new perspective for me.

If your prompt is slow, where would you look first? Because that is the problem, the async_prompt is solving.

**Comment by andreiborisov** [comment]
> If your prompt is slow, where would you look first? Because that is the problem, the async_prompt is solving.

Probably in the GitHub issues😅

Good performance is an expectation by default. In general, if there is a slowdown it will be considered as a bug/non-expected behavior by most people. So, in my opinion, this information should be put somewhere where everyone will see it, e.g. the installation section.

**Comment by andreiborisov** [comment]
> I've some weird things on my Ubuntu machine, but that could be related to being my Ubuntu machine 🤪. Please give me a couple of more days to test it.

@mickimnet what is the nature of your issues? Maybe @acomagu can help.

**Comment by mickimnet** [comment]
> > I've some weird things on my Ubuntu machine, but that could be related to being my Ubuntu machine 🤪. Please give me a couple of more days to test it.
> 
> @mickimnet what is the nature of your issues? Maybe @acomagu can help.

Not worry, was something with permissions, I fixed it. As the Ubuntu machine is kind of dying and will soon™️ be replaced by a NixOS machine, I consider it a non-issue.

Besides: I finished fiddling around with the `async_prompt` function and it works very nice.

**Comment by mickimnet** [comment]
> > If your prompt is slow, where would you look first? Because that is the problem, the async_prompt is solving.
> 
> Probably in the GitHub issues😅

😆 Dang. Not possible to put it there ;)
 
> Good performance is an expectation by default. In general, if there is a slowdown it will be considered as a bug/non-expected behavior by most people. So, in my opinion, this information should be put somewhere where everyone will see it, e.g. the installation section.

The _Installation_ section is to big already and will be overhauled eventually. That would leave the _Advanced Installation_ section.

PS: btw, @chipbuster, as Andrei answered where he would put the _right prompt_ info: where would you put it?

**Comment by andreiborisov** [comment]
I'm closing this due to inactivity, if someone wants to work on this, you're welcome 🙌🏻

**Pull request closed without merging**
