### PR TITLE
fix(gcloud): respect overrides of the active cloud config

### LINKED ISSUE #1845: Google Cloud module should respect the `CLOUDSDK_ACTIVE_CONFIG_NAME` variable
When set this variable overrides the active configuration name; it is not currently respected meaning that the shell may display incorrect gcloud details

### PR DESCRIPTION
**Pull request by jkp**
The active gclould configuration name can be overridden by setting the shell variable `CLOUDSDK_ACTIVE_CONFIG_NAME`. This patch ensures that a manual override is respected by the gcloud module: previous behaviour was to always look at the globally active config name which is lower in precedence than the contents of this variable. Fixes #1845.

### CODE REVIEW

**Review by andytom — COMMENTED** [review]
@jkp thanks for the contribution, this change LGTM but can you add a test case for this.

**Comment by jkp** [comment]
yeah will do...just haven't had a chance to get back to it - busy week at work so far.

**Comment by jkp** [comment]
@andytom pushed with a test case now.

**Review by andytom — APPROVED** [review]

**Comment by andytom** [comment]
@jkp, thank you for the contribution.

**Pull request merged**
