### PR TITLE
docs(i18n): Translate #367 to Japanese

### PR DESCRIPTION
**Pull request by cappyzawa**
Thanks for translation, @bookun :tada:

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/3018/ja/review/10466)

https://github.com/starship/starship/pull/379/commits/578d8fb554f418b3aca1d8b817bdf8679d4dc671 is translated by @bookun, describes #367 .

And I reflected 8f03c14582ad61bf4f95a6b69642d8 to Japanese doc.

### CODE REVIEW

**Comment by cappyzawa** [comment]
I have reviewed https://github.com/starship/starship/pull/379/commits/578d8fb554f418b3aca1d8b817bdf8679d4dc671, and LGTM 👍 

@bookun Could your review other commits, please :pray:

**Comment by bookun** [comment]
I have reviewed your change points.
LGTM🎉

**Comment by matchai** [comment]
Quick as ever! 🏎💨
Thank you for staying on top of this. 😄

**Comment by cappyzawa** [comment]
@all-contributors Please add @bookun for translation.

**Pull request merged**
