### PR TITLE
feat(formatter): Allow scoped variables

### PR DESCRIPTION
**Pull request by heyrict**
#### Description
This PR improves the format string parser, including the following briefly.

- Allow scoped variables (`${var}`), which means:
  - it would be possible to append some characters after a variable, e.g. `${var}s`
  - it would be possible to add some additional parameters to a variable, e.g. `${env:HOST}`
- Add documentation to the spec
- Simplification of the spec
- Confine some rules
  - In a textgroup `[format](style)`, `style` will not accept escaped characters now. e.g. `[symbol](red \[)` will result in a parse error.
  - String started with a number (0-9) will not be recognized as a valid variable name now. e.g. `$9var` will result in a parse error.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by jletey** [comment]
@heyrict Did you mean to merge this into `feat/format-string` instead of `master`? This would help a lot when refactoring the `env_var` module, and this doesn't seem to have any breaking changes.

**Comment by heyrict** [comment]
Yes, all the module refactoring will be merged to `feat/format-string`, and the branch will be merged to master once all the "todo" things are done in the umbralla issue.

Of course, you can open a PR over `feat/format-string` if you want to refactor the `env_var` module.

**Comment by jletey** [comment]
@heyrict Is there a way to change all of my other open PRs to be merged into `feat/format-string`?

**Comment by heyrict** [comment]
There is a menu of target branch when you edit your PR. I can edit that when merging as there aren't any conflicts.

**Pull request merged**
