### PR TITLE
style: improve fish init readibility

### PR DESCRIPTION
**Pull request by pickfire**
- remove semi-colons
- remove first blank line

#### Description

Use fish conventional style when generating the `init`, better readability if people did not `eval`.

#### Motivation and Context

Just improved readability that the fish code have the same style as most of the other fish code.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by matchai** [comment]
Hey @pickfire! Thank you for opening a PR. 😄 
As much as I agree that this would make for more idiomatic fish code, I believe fish's `eval` does not preserve newlines, so the semicolons are necessary.

Could you please try running this locally to confirm?

**Comment by chipbuster** [comment]
This breaks on my machine :( I think it has the right idea though.

Is there any way to get eval to evaluate these things as different lines (maybe if we tried to treat them as files by using [heredocs](https://en.wikipedia.org/wiki/Here_document) and then using `source` instead of `eval`?)

The added complexity of having everything on one line makes it hard to figure out whether something is going to work (and when it breaks, why it broke)

**Comment by matchai** [comment]
I'm going to close this PR as it is for now.
If we find an alternate solution that works, we can open a fresh PR for it. 🙂

**Comment by pickfire** [comment]
Oh, I did not know that this breaks though. Sorry about that.

**Pull request closed without merging**
