### PR TITLE
fix: add missing project filter rules

### PR DESCRIPTION
**Pull request by vladimyr**
#### Description

Add missing project filter rules.

#### Motivation and Context

Without necessary wiring respective config sections are ignored. :warning:   

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by andytom — APPROVED** [review]

**Comment by andytom** [comment]
Good catch @vladimyr, thanks for the quick fix.

**Comment by Milo123459** [comment]
Oh god, these are all modules I added, my bad!

If I may ask, why are we always adding these checks? Or should I just remove the ones that default to nothing and do nothing from my modules I've added?

**Comment by Milo123459** [comment]
Oh and, why don't we just have a universal .scan function that just calls all 3 under-the-hood? Surely this'd clean up code?

**Comment by andytom** [comment]
> Oh god, these are all modules I added, my bad!
> 
> If I may ask, why are we always adding these checks? 

We are adding these to make it possible for uses to configure when the module is triggered. For example I might want to have it so that any directory that contains a file called `some_rust_project` activates the `rust` module. Having these settings allows users to do that.

>Or should I just remove the ones that default to nothing and do nothing from my modules I've added?
 
No these options should be consistent across the all modules.

**Pull request merged**
