### PR TITLE
fix: Be more restrictive with bash init fallback

### PR DESCRIPTION
**Pull request by nickwb**
Changes the bash init fallback to be `Major Version > 3` rather than `Major Version > 4`.

#### Description
The issue being worked around affects bash 3.2, so `Major Version > 3` is sufficient.
The fallback requires `/dev/stdin`, which may not exist on all systems - so it's preferable to use the normal bootstrap when possible.

This should fix starship for some Windows users who are using bash without full POSIX emulation.

For example: Git Bash, which is part of Git for Windows, does not recognise `/dev/stdin`, but does ship with bash 4.x.

#### Motivation and Context
Improve support for starship on Windows 😃 

Bash on Windows is a bit of a minefield, because there are various projects maintaining various POSIX emulation layers and various patch lists. This change will not fix starship for ALL bash users on windows, but it should fix it for a portion of them.

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?
- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

(I did specifically test this on bash 3.2 on MacOS).

#### Checklist:
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by chipbuster** [comment]
@nickwb Do you know what minor version git bash ships with specifically? I ask because we discovered while testing #241 that for some reason, the standard init pattern doesn't work with bash-4.0. The earliest version I can confirm it working with is 4.1.

**Comment by nickwb** [comment]
Git for Windows 2.22.0 and 2.23.0 (the latest) both ship with bash: `GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)`.

Sadly there is some regression in 2.23.0, because `eval "$(starship init bash)"` is broken in 23, but works fine in 22.

Bash 4.4.23 seems to have been around since 2.22.0 (December 2018), and Bash 4.4.x for numerous years before that.

**Comment by nickwb** [comment]
@chipbuster - Do you think we should take the `bash >= 4.1` logic that was proposed at one point for #241?

Based on the versions of Git Bash I mentioned in the previous comment, v4.1 as a minimum should be suitable for everyone who has installed/updated Git for Windows in the last few years.

**Comment by chipbuster** [comment]
@nickwb I think that's probably the best way to go here. It won't be perfect, but we'll be supporting a lot more configurations than we are now.

**Comment by nickwb** [comment]
@chipbuster - Ok, I've pushed an update as discussed.

**Comment by chipbuster** [comment]
@nickwb Please leave a comment reminding me to add you to all-contributors once #276 is merged.

**Pull request merged**
