### PR TITLE
ci: set changelog types for release-please

### PR DESCRIPTION
**Pull request by matchai**
#### Description

Set changelog types to add "perf" and "refactor" conventional commits to our changelog.

### CODE REVIEW

**Comment by davidkna** [comment]
By the way, I checked and perf is already included by default in the changelog.

**Comment by matchai** [comment]
Would you be opposed to leaving it as the defaults then?
We could search for refactors in the commit history rather than the changelog.

**Comment by davidkna** [comment]
@matchai  I'm not opposed to leaving the defaults.

**Comment by matchai** [comment]
In that case, I think it would be simplest and easiest to leave it as-is then.
I felt that our current changelogs list a few too many things that aren't actionable or valuable for our users. I think the defaults make sense. 👍

**Pull request closed without merging**
