### PR TITLE
build: Add snapcraft.yaml to build snap of starship

### PR DESCRIPTION
**Pull request by popey**
Adds support for building snaps out of starship.

This enables `snapcraft` to build a snap of `starship` which can then be published in the Snap Store. As discussed over email I published a build of `starship` to the Snap Store, and offered to hand this over to the upstream developers.  I have [requested](https://forum.snapcraft.io/t/please-transfer-starship-to-matankushner/14558) the transfer on the snapcraft forum.

#### Description

Using the snapcraft command line utility on a Linux developer machine, in CI, or using build.snapcraft.io, this yaml will build a strictly confined snap of starship. It has a conditional build section. 

If hooked up to build.snapcraft.io - the following will happen.

  * On each commit, a new build will be triggered, and published to the edge channel in the Snap Store. Users who wish to try out the latest builds can `snap install starship --edge` or `snap refresh starship --edge` (if they already have it installed).
  * On stable releases, where there is a new git tag, it will build the stable release, as the version is higher than the one in the `beta` channel.  This enables us to use one yaml to build both `edge` and `beta`/`stable` builds. Once the build is published into the `edge` channel, it can be promoted to the `stable` channel after testing.

#### Motivation and Context

Publishing in the Snap Store can make it easier for Linux uses to install starship & obtain automatic updates. It can also raise awareness of the application via promotion in the Snap Store social channels, and being featured.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [X] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

I don't believe the documentation should be updated until some extensive testing of the snap has been performed. Once this lands, I

### CODE REVIEW

**Comment by popey** [comment]
The application has now been transferred to your account. https://forum.snapcraft.io/t/please-transfer-starship-to-matankushner/14558/2

**Comment by Marsup** [comment]
Hi, this might not be the perfect place for a discussion, but do you know what to expect in terms of performance compared to the raw binary?

**Comment by popey** [comment]
@Marsup Should be no notable difference.

**Comment by matchai** [comment]
@all-contributors Please add @popey for infra.

**Pull request merged**
