### PR TITLE
docs: Include Docker related information in CONTRIBUTING

### PR DESCRIPTION
**Pull request by Hofer-Julian**
#### Description
Includes instruction to set up and use Docker.

#### Motivation and Context
Using Docker is hard.
Additional guidance might be helpful.

### CODE REVIEW

**Comment by chipbuster** [comment]
@Hofer-Julian Did you end up deciding against including information on the individual build/run steps?

**Comment by Hofer-Julian** [comment]
I wasn't sure if it still makes sense, when the SELinux problem is resolved in the script and both commands still have to be executed regularly. What do you think?

**Comment by chipbuster** [comment]
> I wasn't sure if it still makes sense, when the SELinux problem is resolved in the script and both commands still have to be executed regularly.

That makes sense. It'll probably be a little more reasonable to add in those changes once we stabilize our modules a bit.

**Comment by chipbuster** [comment]
@all-contributors please add @Hofer-Julian for doc!

**Pull request merged**
