### PR TITLE
fix(bash): use `eval` instead of a procsub for the POSIX mode

### LINKED ISSUE #1674: Lightdm session won't start because of failed eval of starship
#### Current Behavior
Lightdm greeter goes through authentication and goes back to login screen as soon as it evaluates starships line in `.bashrc` making it impossible to login. Manually sourcing `.bashrc` from terminal with starship works correctly.

#### Expected Behavior
Starship correctly evaluating and lightdm session starting.

#### Additional context/Screenshots
Content of `~/.xsession-errors`
```
/home/wojtek/.bashrc: eval: line 3: syntax error near unexpected token `('
/home/wojtek/.bashrc: eval: line 3: `source <("/usr/bin/starship" init bash --print-full-init)'
```
#### Environment
- Starship version: 0.44.0
- bash version: GNU bash, version 5.0.18(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- Operating system: Arch Linux
- Terminal emulator: Alacritty 0.6.0-dev

#### Relevant Shell Configuration

```bash
eval "$(starship init bash)"
```

#### Starship Configuration

```toml
<unknown config>
```

### LINKED ISSUE #5382: Error on launching with Kitty Terminal
#### Current Behavior

getting the below error when launching kitty. Works as per expected with iterm2.

I am using bash shell.

```
 -bash: eval: line 8: syntax error near unexpected token `('
-bash: eval: line 8: `                    source <(/opt/homebrew/bin/starship init bash --print-full-init)'
```

#### Environment
- Starship version: 1.16.0
- <unknown shell> version: <unknown version>
- Operating system: Mac OS 13.5.0
- Terminal emulator: <unknown terminal> <unknown version>
- Git Commit Hash: 
- Branch/Tag: 
- Rust Version: rustc 1.71.0 (8ede3aae2 2023-07-12) (built from a source tarball)
- Rust channel:  release
- Build Time: 2023-07-30 13:30:05 +00:00
#### Relevant Shell Configuration

```bash
<unknown config>
```

#### Starship Configuration

```toml
add_newline = true

[git_status]
disabled = false

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = false

[battery]
disabled = true

[python]
disabled = true

[cmake]
disabled = true

[directory]
read_only = "(read only)"

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '

```

### PR DESCRIPTION
**Pull request by akinomyoga**
#### Description

Use `eval -- "$(/path/to/starship init bash --print-full-init)"`, which works in any version of Bash and also in the POSIX mode, instead of the current version of `source <(...)` which does not work when the POSIX mode is turned on in Bash <= 5.0. I have added a detailed explanation in the code comments.

#### Motivation and Context

~~In Bash 5.0 and below~~ (**edit**: After I submitted this PR, #5735 introduced the approach using `PS0` for Bash 4.4 and above, so the problem arises only in Bash 4.3 and below as of 2024-04-01), Starship initialization failed when the POSIX mode is turned on. This PR fixes the issue.

Closes #1674
Closes #3660
Closes #5382

#### Screenshots (if appropriate):

With the following `bashrc`:

```bash
# bashrc
set -o posix
eval "$(starship init bash)"
```

Before the fix:
image

After the fix:
image

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.

There doesn't seem to be any documentation about the internal implementation of the original approach `<(...)`, so I judged we do not have to add documentation for the new approach either.

- [ ] I have updated the tests accordingly.

I'm not familiar with Rust, but `cargo check` just seems to pass.

### CODE REVIEW

**Comment by akinomyoga** [comment]
@davidkna Could you take a look at this PR? I just wanted to submit another PR to solve the issues with the `DEBUG` trap, but to explain the problem the coming PR tries to solve, I need this PR.

Maybe the code coverage error in the CI blocks the reviewing but I'd like some advice about how to fix it (or whether I should fix it in the first place because I think the part I modified wasn't covered by the test even before this change. In the part to which `codecov` issues an error, I haven't added any code but only changed the content of the string literal).

**Comment by akinomyoga** [comment]
I think this PR also solved the problem that PR #3660 tried to solve. The problem PR #3660 attempts to solve is that `trap -p DEBUG` is called inside a function `_main` and `source`, so the DEBUG trap at the top level is not captured by `trap -p DEBUG`. To solve the problem, PR #3660 tried to temporarily set `set -o functrace` to make all the `DEBUG` trap handlers inherited by the child function calls, which is a global behavioral change of the entire shell. However, the problem disappears with the PR because this PR makes `trap -p DEBUG` executed at the top level.

**Review by davidkna — APPROVED** [review]
LGTM

**Comment by akinomyoga** [comment]
Thank you for your quick response! If there is anything additional needed, please let me know.

**Comment by andytom** [comment]
Thank you for your contribution @akinomyoga and thanks for reviewing @davidkna.

**Comment by akinomyoga** [comment]
Thank you!

**Pull request merged**
