### PR TITLE
fix(python): Read venv prompt from pyvenv.cfg

### LINKED ISSUE #1698: Python: incorrect virtual environment name in prompt (when using --prompt option)
#### Current Behavior
When a new virtual environment is created with a custom prompt name (using the venv module and [`--prompt option`](https://docs.python.org/3/library/venv.html)):

```python
python -m venv --prompt customname venv
```

the name of the virtual environment displayed in prompt is `venv` instead of `customname`.

That's because the custom prompt name gets hardcoded in the activation script:
```shell
# venv/bin/activate
...
if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1:-}"
    if [ "x(customname) " != x ] ; then
	PS1="(customname) ${PS1:-}"
    else
    if [ "`basename \"$VIRTUAL_ENV\"`" = "__" ] ; then
        # special case for Aspen magic directories
        # see http://www.zetadev.com/software/aspen/
        PS1="[`basename \`dirname \"$VIRTUAL_ENV\"\``] $PS1"
    else
        PS1="(`basename \"$VIRTUAL_ENV\"`)$PS1"
    fi
    fi
    export PS1
fi
```

and starship takes the name of the file from the `VIRTUAL_ENV` variable (which points to a folder containing the virtual environment, not the name of the virtual environment): https://github.com/starship/starship/blob/bb324834a515e18ca7a913ad6248cb8049e3ec33/src/modules/python.rs#L110.

#### Expected Behavior
The correct venv name should be displayed.

#### Additional context/Screenshots
Here is the difference between fish running starship and zsh without starship (type of the shell doesn't matter, fish displays correct virtual environment name when starship is not used):

zsh__Users_switowski_workspace_playground_test_venv_bin

#### Possible Solution

Unfortunately, I don't know how it can be solved without running a regular expression to extract the virtual environment name from the activation script.

#### Environment
- Starship version: 0.44.0
- fish version: fish, version 3.1.0
- Operating system: Mac OS 10.15.6
- Terminal emulator: iTerm.app 3.3.12

#### Relevant Shell Configuration

```bash
set default_user switowski
set default_machine smbp

# Set locale to avoid various error messages
set -x LC_ALL en_US.UTF-8
set -x LANG en_US.UTF-8

# Disable installing pip packages outside of virtualenv
# To override run: PIP_REQUIRE_VIRTUALENV="" pip ...
set -x PIP_REQUIRE_VIRTUALENV true

source ~/.config/fish/path.fish
source ~/.config/fish/aliases.fish
source ~/.config/fish/functions.fish

# for things not checked into git..
if test -e "$HOME/.extra.fish";
  source ~/.extra.fish
end

# For pipx:
# Created by `userpath` on 2019-11-12 17:26:16
set PATH $PATH /Users/switowski/.local/bin
register-python-argcomplete --shell fish pipx | .

# fisher-done settings:
set -x __done_min_cmd_duration 10000  # set to 10s (default is 5s)

# Start starship prompt
starship init fish | source

# Use Docker BuildKit
set -x COMPOSE_DOCKER_CLI_BUILD 1
set -x DOCKER_BUILDKIT 1

# zoxide (z replacement)
zoxide init fish | source

# For rbenv
#set -x RUBY_CONFIGURE_OPTS "--with-openssl-dir=(brew --prefix openssl@1.1)"  # This doesn't work!
set -x RUBY_CONFIGURE_OPTS "--with-openssl-dir=/usr/bin/openssl"
```

#### Starship Configuration

```toml
[directory]
truncation_length = 8

```

### PR DESCRIPTION
**Pull request by Tadaboody**
#### Description

Add parsing of pyvenv.cfg to handle when a user creates a venv and passes the `--prompt` option
#### Motivation and Context

Closes #1698 

#### Screenshots (if appropriate):
image

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [?] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Review by gaborbernat — APPROVED** [review]
🚀

**Review by andytom — APPROVED** [review]
LGTM

**Comment by andytom** [comment]
@Tadaboody thanks for the quick fix and @gaborbernat thank you for reviewing.

**Comment by Tadaboody** [comment]
@andytom If it's alright could you tag this with [`hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/hacktoberfest-update)?

**Pull request merged**
