### PR TITLE
feat: READMEs: add Nix instructions

### PR DESCRIPTION
**Pull request by bbigras**
#### Description
Edited both READMEs

#### Motivation and Context
Tell people how to install starship on Nix

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by bbigras** [comment]
We could also do:

   #### Nix (unstable)

   ```sh
   $ nix-env -i starship
   ```

until the next Nix release

**Comment by bbigras** [comment]
I think I prefer the simpler "Nix (unstable)" one-line instructions. I would think Nix users are expected to know how to use "stable" vs "unstable" channels.

**Comment by matchai** [comment]
> I think I prefer the simpler "Nix (unstable)" one-line instructions.
I haven't used Nix so I'll trust your judgment. 👍

**Comment by bbigras** [comment]
I made the change and rebased. It's ready for review/merge.

**Comment by matchai** [comment]
Thank you for your contribution, Bruno! 😄

**Pull request merged**
