### PR TITLE
feat: add time module

### PR DESCRIPTION
**Pull request by khubo**
Display time in the shell

#### Description
Add a module that will display time

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:
- [x] Add the feature
- [ ] Support formatting of time in config file (`starship.toml`)
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by khubo** [comment]
closing this since already a PR exist.

**Comment by chipbuster** [comment]
@khubo This is sorta our bad--we probably should have marked the time issue as being assigned already, especially given that the PR has been open for a while now :grimacing:

The code in here looks pretty good. Would you perhaps be willing to work on another outstanding issue? We currently have #157 and #149 which could both use some work.

**Comment by khubo** [comment]
@chipbuster sorta my fault too. I should have gone through the entire thread. Anyhow, I will pick on those issues and make another PR!

**Comment by chipbuster** [comment]
@khubo Looks like matchai just opened #158 as well.

If you do decide to start writing code for an issue, make sure to assign yourself on the issue so we don't repeat this episode! You can always drop yourself later if you discover it's harder than you thought or life takes over (we've already had that happen a few times and it's not a huuge deal, so don't feel like you're committing to having a working solution)

**Pull request closed without merging**
