### PR TITLE
fix(install): Detect cygwin_nt as Windows

### LINKED ISSUE #985: requesting a build for x86_64-cygwin_nt-10.0
Can we get staship available for cygwin?

$ curl -fsSL https://starship.rs/install.sh | bash

  Configuration
> Bin directory: /usr/local/bin
> Platform:      cygwin_nt-10.0
> Arch:          x86_64

> Tarball URL: https://github.com/starship/starship/releases/latest/download/starship-x86_64-cygwin_nt-10.0.tar.gz
? Install Starship latest to /usr/local/bin? [y/N] y
> Installing Starship, please wait…

x Command failed (exit code 22): curl --silent --fail --location https://github.com/starship/starship/releases/latest/download/starship-x86_64-cygwin_nt-10.0.tar.gz

> This is likely due to Starship not yet supporting your configuration.
> If you would like to see a build for your configuration,
> please create an issue requesting a build for x86_64-cygwin_nt-10.0:
> https://github.com/starship/starship/issues/new/

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

### LINKED ISSUE #2103: requesting a build for x86_64-cygwin_nt-10.0
``` sh
$ curl -fsSL https://starship.rs/install.sh | bash

  Configuration
> Bin directory: /usr/local/bin
> Platform:      cygwin_nt-10.0
> Arch:          x86_64

> Tarball URL: https://github.com/starship/starship/releases/latest/download/starship-x86_64-cygwin_nt-10.0.tar.gz
? Install Starship latest to /usr/local/bin? [y/N] y
> Installing Starship, please wait…

x Command failed (exit code 22): curl --silent --fail --location https://github.com/starship/starship/releases/latest/download/starship-x86_64-cygwin_nt-10.0.tar.gz

> This is likely due to Starship not yet supporting your configuration.
> If you would like to see a build for your configuration,
> please create an issue requesting a build for x86_64-cygwin_nt-10.0:
> https://github.com/starship/starship/issues/new/\n

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

```

os window10
terminal cygwin
Could this happen?
Thanks.

### PR DESCRIPTION
**Pull request by andytom**
#### Description

This fixes the install script by detecting `cygwin_nt*` as Windows.

#### Motivation and Context

Closes #985
Closes #2103 

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by davidkna** [comment]
I tried it and the install script and it work as such, but I found some issues:

- `/usr/local/bin/starship.exe` was not executable. Maybe add a `chmod`?
- `eval "$(/usr/local/bin/starship init bash)"` doesn't appear to work. 
  ```
   $ eval "$(/usr/local/bin/starship.exe init bash)"
  -bash: C:\tools\cygwin\usr\local\bin\starship.exe: command not found
   ```
- Using the second stage directly didn't work either:
  ```
  $ source <("/usr/local/bin/starship.exe" init bash --print-full-init)
  -bash: $'\r': command not found
  -bash: $'\r': command not found
  -bash: $'\r': command not found
  -bash: /dev/fd/63: line 16: syntax error near unexpected token `$'{\r''
  'bash: /dev/fd/63: line 16: `starship_preexec() {
  ```

**Comment by andytom** [comment]
Hmm, looks like I should have checked the other issues a bit more, it looks like we have some issues running under cygwin see #1354, I'm going to pop this PR on hold until we have resolved that issue.

**Comment by andytom** [comment]
Now that #2020 has been merged I think #1354 should be fixed so I'm going to remove this from being on hold.

**Comment by chipbuster** [comment]
Testing in a fresh Cygwin install reveals two stumbling blocks on my end:

- `unzip` is not installed by default, so the install script chokes at that step.
- Once installed to the default location (`/usr/local/bin`), another existing install of starship will interfere with it, possibly because Cygwin is reading its PATH values from Windows:
   ```
   $ eval "$(starship init bash)"
   -bash: C:\Users\chipb\scoop\apps\starship\current\starship.exe: command not found
   ```

I think the latter issue we *probably* don't have to worry about much, since people like me (who have starship installed as curl'ed binary, as choco, as scoop, and within WSL) are not very common. For the former, I don't think there's much we can do, since you have to run the Cygwin setup binary to install new packages, and we have no idea where that's located. Just something to be aware of.

I'm also currently getting an issue where the `starship` path that's being put into the second-phase init is `C:\cygwin64\usr\local\bin\starship.exe` instead of `/usr/local/bin/starship` like it should be, but that's probably because the patches in #2020 aren't in a release yet.

**Review by chipbuster — APPROVED** [review]
I think we're good to go. A few issues I hit to be aware of (see other comment), but I don't think we can really solve them programmatically.

**Pull request merged**
