### PR TITLE
fix(git_status): Fix when the worktree != root dir

### LINKED ISSUE #2808: Git status do not appear when .git folder location is not the same as worktree location
To reproduce issue:
1. `git clone` into a folder `$HOME/some_folder` and git status appears in prompt
2. Copy all the files from `some_folder` to `$HOME` folder
3. Set `git worktree` with an absolute path by `git config core.worktree <absolute path of $HOME>`
4. However the .git folder stays `some_folder`
5. git status no longer appears in prompt, however `git status` still works under `some_folder`

### PR DESCRIPTION
**Pull request by andytom**
#### Description

Have updated the git_status module to work if the worktree has been
changed to a different directory than the repository root directory.

#### Motivation and Context

Closes #2808

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by kidonng** [comment]
There is another scenario not mentioned in the original issue where git works but starship doesn't, but I can't remember it now. Will test this later and try to remember that one.

**Comment by kidonng** [comment]
OK, I remembered that one: `git init --separate-git-dir`. However this PR doesn't work with it or the original issue in my local test:

```
~ 
❯ git clone https://github.com/kidonng/fisher_path.fish
Cloning into 'fisher_path.fish'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 27 (delta 9), reused 19 (delta 5), pack-reused 0
Receiving objects: 100% (27/27), 4.19 KiB | 4.19 MiB/s, done.
Resolving deltas: 100% (9/9), done.

~ 
❯ mkdir backup

~ 
❯ cd fisher_path.fish/

fisher_path.fish on  master 
❯ mv * ../backup/

fisher_path.fish on  master [✘] 
❯ git config core.worktree (realpath ../backup/)

~/fisher_path.fish
❯
```

```
~ 
❯ git init --initial-branch=main --separate-git-dir=git worktree
Initialized empty Git repository in /private/var/folders/gv/4whvwttx0p77d2mvhfnk46jc0000gn/T/tmp.QEIAjtPQ/git/

~ 
❯ cd worktree/

tmp.QEIAjtPQ/worktree 
❯ /Users/kid/Developer/starship/target/debug/starship --version
starship 0.55.0
branch:fix/git_different_workdir
commit_hash:20eb06b8
build_time:2021-06-30 21:29:33
build_env:rustc 1.52.1,
```

**Comment by andytom** [comment]
Both of those work for me

```
/tmp/tmp.SIfsV566EX 
❯ git clone https://github.com/kidonng/fisher_path.fish
Cloning into 'fisher_path.fish'...
...
/tmp/tmp.SIfsV566EX 
❯ mkdir backup
/tmp/tmp.SIfsV566EX 
❯ cd fisher_path.fish/
/t/t/fisher_path.fish on  master 
❯ mv * ../backup/
/t/t/fisher_path.fish on  master [✘] 
❯ git config core.worktree  $PWD/../backup/
/tmp/tmp.SIfsV566EX/fisher_path.fish 
❯ touch ../backup/test
/tmp/tmp.SIfsV566EX/fisher_path.fish [?] 
```

```
/tmp/tmp.qVM9fITGGt 
❯ git init  --separate-git-dir=git worktree
Initialized empty Git repository in /tmp/tmp.qVM9fITGGt/git/
/tmp/tmp.qVM9fITGGt 
❯ cd worktree/
/t/tmp.qVM9fITGGt/worktree 
❯ touch test
/t/tmp.qVM9fITGGt/worktree [?] 
❯ 
```

**Comment by kidonng** [comment]
Interesting, the appearance is deceiving, it does work but the branch is not showing. Is this a limitation of git2?

**Comment by andytom** [comment]
> Interesting, the appearance is deceiving, it does work but the branch is not showing. Is this a limitation of git2?

Ah this PR only fixes the issue in the git_status module, I haven't had time to work on the other git_* modules yet. As part of that I would like to also switch them over to calling git and parsing the output rather than using libgit2 too.

**Pull request merged**
