### PR TITLE
fix(xonsh): remove `| cat` workaround from xonsh init

### LINKED ISSUE #3646: Failed to init on Xonsh
#### Current Behavior
Starship failed to init on Xonsh shells. Tested under macOS and WSL

#### Expected Behavior
Starship can init on zsh (macOS) and bash (WSL), but cannot work on Xonsh shells.

#### Additional context/Screenshots
The full traceback is too long to be put into this issue, so I put it [here](https://pastebin.com/5sr9A5Dg)

#### Environment
- Starship version: 1.3.0
- zsh version: zsh 5.8 (x86_64-apple-darwin21.0)
- Operating system: Mac OS 12.2.1
- Terminal emulator: iTerm.app 3.4.15
- Git Commit Hash: 
- Branch/Tag: 
- Rust Version: rustc 1.58.1
- Rust channel:  release
- Build Time: 2022-02-07 14:56:29 +00:00

#### Relevant Shell Configuration

```bash
# Default editor config
if type nvim &>/dev/null; then
  export EDITOR="nvim"
fi

# Homebrew config
# export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
# export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
# export HOMEBREW_CASK_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
# Homebrew zsh shell completion
if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

# OpenJDK for compiler
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

# iTerm2 utils
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Starship prompt
eval "$(starship init zsh)"
```

#### Starship Configuration

```toml
add_newline = false 

format = """
$username\
$hostname\
$battery\
$jobs\
$memory_usage\
$time\
$shlvl\
$aws\
$env_var\
$line_break\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$cmake\
$dotnet\
$golang\
$java\
$julia\
$nodejs\
$php\
$python\
$ruby\
$rust\
$custom\
$line_break\
$status\
$character"""

[aws]
symbol = ""

[battery]
unknown_symbol = ""
format = "[$symbol $percentage]($style) "
[[battery.display]]
threshold = 20
style = "bold red"
[[battery.display]]
threshold = 50
style = "bold yellow"
[[battery.display]]
threshold = 80
style = "bold green"
[[battery.display]]
threshold = 95
style = "bold blue"
[[battery.display]]
threshold = 100
style = "bold purple"

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[command_timeout]
disabled = true

[dart]
symbol= " dart"

[directory]
truncation_symbol = "/"
read_only = ""
read_only_style = "bold bright-red"
style = "bold bright-cyan"
format = "[$read_only]($read_only_style)[ $path ]($style)"

[docker_context]
symbol = " docker "

[dotnet]
symbol = " dotnet "

[elixir]
symbol = " elixir "

[elm]
symbol = " elm "

[erlang]
symbol = " erlang "

[git_branch]
symbol = "  "
format = "[$symbol$branch]($style)"

[git_state]
rebase = " REBASING"
merge = " MERGING"
revert = " REVERTING"
cherry_pick = " CHERRY-PICKING"
bisect = " BISECTING"
am = " AM"
am_or_rebase = " AM/REBASE"

[git_status]
ahead = "⇡"
behind = "⇣"
conflicted = "!"
deleted = "×"
diverged = "⇕"
modified = "*"
renamed = "»"
staged = "+"
stashed = "◌"
untracked = "?"
format = "([\\[$staged$modified$conflicted$untracked$stashed$renamed$deleted$ahead$behind$diverged\\]]($style)) "

[golang]
symbol = " golang "

[hostname]
ssh_only = false
style = "bold green"
format = "[ $hostname]($style) "

[java]
symbol = " java "

[jobs]
symbol = "華"

[julia]
symbol = " julia "

[kotlin]
symbol = "🅺 kotlin "

[lua]
symbol = " lua "

[memory_usage]
disabled = false
symbol = ""
format = "[$symbol \\[${ram_pct}(|${swap_pct})\\]]($style) "
threshold = -1

[hg_branch]
symbol = " "

[nodejs]
symbol = " nodejs "

[package]
symbol = " "

[perl]
symbol = " perl "

[php]
symbol = " php "

[purescript]
symbol = "亮 purescript "

[python]
symbol = " python "
python_binary = ["python3", "python2"]

[ruby]
symbol = " ruby "

[rust]
symbol = " rust "

[status]
disabled = false
symbol = ""
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﳼ"
signal_symbol = ""
map_symbol = true
format = "[$symbol $common_meaning$signal_name ]($style)"

[swift]
symbol = "ﯣ swift "

[time]
disabled = false
format = '[ \[$time\]]($style) '
time_format = "%T"
style = "bold bright-black"

[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = "[ $user]($style) "

```

### LINKED ISSUE #3795: xonsh init requires updates and isn't reading starship.toml
#### Current Behavior

Using the latest `xonsh` version 0.11.0, there are 2 key issues:
1. Using the `execx($(starship init xonsh))` results in an error starting up.  Details below on resolution
2. starship is not reading from my `~/.config/starship.toml` in xonsh at all
3. In comparing the screenshots, I'm not positive the bash prompt is fully working either?  you may see something I'm missing

#### Expected Behavior

This config works with bash, and the expectation is xonsh should read it as well.

## Screenshot from bash
starship-bash

## Screenshot from xonsh:
starship-xonsh

## Solution to item 1 above

In the `--print-full-init`, there is a comment:

```
# The `| cat` is a workaround for https://github.com/xonsh/xonsh/issues/3786. See https://github.com/starship/starship/pull/2807#discussion_r667316323.
```
That issue is now resolved, so the code can now be

```
...
    return $(starship prompt --status=@(status) --jobs=@(jobs) --cmd-duration=@(duration))
...
    return $(starship prompt --status=@(status) --jobs=@(jobs) --cmd-duration=@(duration) --right)
```

#### Environment
```
xonsh on  HEAD (337cf25) [?] via 🐍 v3.9.8 on ☁️   
❯ starship --version
starship 1.5.4
tag:v1.5.4
commit_hash:d420a63e
build_time:2022-03-24 19:18:47 +00:00
build_env:rustc 1.59.0 (9d1b2106e 2022-02-23),

xonsh on  HEAD (337cf25) [?] via 🐍 v3.9.8 on ☁️   
❯ xonsh --version
xonsh/0.11.0

Shell is Tabby

xonsh on  HEAD (337cf25) [?] via 🐍 v3.9.8 on ☁️   
❯ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
```

#### Relevant Shell Configuration
This should only be in `~/.xonshrc`:

## ~/.xonshrc

```
$STARSHIP_CONFIG='~/.config/starship.toml'
execx($(starship init xonsh))
```

## starship.toml

```
~/.config 
❯ cat starship.toml 
format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nodejs\
$terraform\
$vagrant\
$aws\
$env_var\
$cmd_duration\
$line_break\
$status\
$shell\
$character"""

right_format = """$time"""

[aws]
disabled = false
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[gcloud]
disabled = false
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[python]
disabled = false
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[sudo]
format = '\[[as $symbol]\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
disabled = false
use_12hr = true
format = '\[[$time]($style)\]'

[username]
disabled = false
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'
```
### Bash starship vars:

```
STARSHIP_CMD_STATUS=0
STARSHIP_CONFIG='~/.config/starship.toml'
STARSHIP_DURATION=131
STARSHIP_END_TIME=1648314730659
STARSHIP_PIPE_STATUS=([0]="0")
STARSHIP_PREEXEC_READY=false
STARSHIP_SESSION_KEY=7918739217744260
STARSHIP_SHELL=bash
STARSHIP_START_TIME=1
```

### Xonsh starship vars
```
❯ [f"{x}: {y}" for x, y in dict(${...}).items() if x.startswith("STARSHIP")]
['STARSHIP_SESSION_KEY: ed492d3dd5b84c458b4dd8b1ae1b6e22',
 'STARSHIP_CONFIG: ~/.config/starship.toml',
 'STARSHIP_SHELL: xonsh']
```

### LINKED ISSUE #4900: xonsh on Windows 11: Starship command can't be found during init
#### Current Behavior
`xonsh` reported if command `starship` can not be found when `xonsh` intializing.

#### Expected Behavior
`starship` should be loaded as expected as shown on image below using PowerShell Core

#### Additional context/Screenshots

image

#### Possible Solution

Launching `starship init xonsh --print-full-init` shown that `\b` (or any backward slashes for that matter) is not escaped:

```py
# $ starship init xonsh --print-full-init
# ...

def starship_prompt():
    # ...
    return $('C:\Program Files\starship\bin\starship.exe' prompt --status=@(status) --jobs=@(jobs) --cmd-duration=@(duration) | cat)

def starship_rprompt():
    # ...
    return $('C:\Program Files\starship\bin\starship.exe' prompt --status=@(status) --jobs=@(jobs) --cmd-duration=@(duration) --right | cat)

# ...
```

I think that those backward slashes must be escaped by doubling it `\\` as the script is in Python. For example:

```py
return $('C:\\Program Files\\starship\\bin\\starship.exe' prompt --status=@(status) --jobs=@(jobs) --cmd-duration=@(duration) | cat)
```

But, if I did manually by copying those lines to the shell directly, it seems that there are missing commands from the shell itself while `$XONSH_TRACEBACK_ENABLE = True` (_yes, I know this is dumb, but if it can show error, why not?_):

image

#### Environment
- Starship version: 1.12.0
- xonsh version: xonsh/0.13.4 installed via `pipx` 1.1.0, Python 3.11.2
- Operating system: Windows 10.0.22621
- Terminal emulator: Windows Terminal Version: 1.16.10261.0
- Git Commit Hash: 
- Branch/Tag: master
- Rust Version: rustc 1.65.0 (897e37553 2022-11-02)
- Rust channel: stable-x86_64-pc-windows-msvc release
- Build Time: 2022-12-13 16:12:46 +00:00
#### Relevant Shell Configuration

```bash
execx($(starship init xonsh))
```

#### Starship Configuration

```toml
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

"add_newline" = false

"format" = """╭─$username$hostname$directory([<](bold yellow)$git_branch$git_status[> ](bold yellow))
╰─$shell$character"""

continuation_prompt = "[>>>](gray) "

# The following styling is inspired by [Bira theme](https://github.com/oh-my-fish/theme-bira)
# for Fish shell.

[username]
disabled = false
style_root = "red bold"
style_user = "green bold"
show_always = true
format = "[$user]($style)"

[hostname]
disabled = false
ssh_only = false
ssh_symbol = "☁ "
format = "[@$hostname](bold green) $ssh_symbol"

[directory]
truncation_length = 0

[git_branch]
disabled = false
format = "[$branch(:$remote_branch)]($style)"
style = "bold yellow"

[git_status]
untracked = "U"
modified = "M"
deleted = "D"
renamed = "R"
stashed = "S"
format = "([*$all_status]($style))"
style = "bold yellow"

[shell]
disabled = false
bash_indicator = "bash"
zsh_indicator = "zsh"
fish_indicator = "><>"
cmd_indicator = "CMD"
powershell_indicator = "pwsh"
unknown_indicator = "???"
format = "[\\[$indicator\\]]($style)"
style = "blue bold"

[character]
success_symbol = "[\\$](bold white)"
error_symbol = "[\\$](bold red)"
format = "$symbol "

[battery]
disabled = true

```

### PR DESCRIPTION
**Pull request by Maxxus220**
Caused by use of cat on Windows platforms.
Removed |cat thanks to davidkna pointing out that the workaround that introduced it has been fixed upstream.

#### Description
Removed cat within starship.xsh as it is no longer needed and causes issues on Windows.

#### Motivation and Context
cat does not work on Windows and causes problems when running starship with xonsh
Closes #4900
Closes #3795
Closes #3646

#### How Has This Been Tested?
Ran starship with xonsh with both the latest release and my fork (the error was removed)
Ran cargo test to ensure tests are still passing
- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by davidkna** [comment]
Instead of this, it might be better to just get rid of the `cat` altogether, since the related upstream issue has been fixed for a while and it has been causing other issues (#3795, #3646).

**Comment by davidkna** [comment]
LGTM, I think it makes sense to remove the cat, given it shouldn't break anything but the error output, the upstream issue has been closed for a while, and the decent number of issues this might help close. The only thing missing is setting an explicit minimum xonsh version everywhere (please have a look at past nushell PRs for reference @Maxxus220).
Since @chipbuster participated in related discussions: Are you good with this?

**Comment by SapphicCode** [comment]
Hey, I also just investigated this very same issue. Is there anything blocking this?

It would improve prompt speeds by ~20ms (on my machine).

**Review by andytom — APPROVED** [review]

**Comment by davidkna** [comment]
Thanks for the contribution @Maxxus220, and thanks for the second review @andytom.

**Pull request merged**
