### PR TITLE
feat: add k8s granular config

### LINKED ISSUE #570: Granular config control by matching text
Came across starship last week, liking it a lot!

#### Describe the solution you'd like
More fine-grained control over style would be nice, the typical use-case being different styles for different environments, ie green for staging, red for production. This provides extra visual feedback when you're running potentially dangerous commands.

A sample config quickly pulled out of a hat could look something like this:

``` toml
[kubernetes]
style = "blue" # Default values if nothing matches
symbol = "🔵"
match = [
    {match = "staging.evilcorp.com", style = "green", symbol = "🍏"},
    {match = "prod.evilcorp.com", style = "red", symbol = "🍎"}
]
```

Using the Kubernetes module as an example here, but suggestion is broad enough to be useful for several other modules.

#### Describe alternatives you've considered
Unaware of alternatives. Open to suggestions!

### PR DESCRIPTION
**Pull request by nomaed**
#### Description
This PR implements the suggestion from https://github.com/starship/starship/issues/570 to add an ability to customize the configuration of the `kubernetes` module style, based on the current context.

A new variable is added to the config section, called `environments`, which is a list of possible customizations. Each such customization is an object with a `name` variable, which includes a possible substring of an context name, and an optional `style` and `icon` that will override the global configuration, if the currently used context matched the `names` (substring match).

#### Motivation and Context
It is common to work with development, testing, staging and production environments when deploying to kubernetes clusters, especially with continuous deployment. However, it is too easy to be using a production context (for example, for inspecting logs) and forgetting to switch to the personal development context when deploying any changes. 

This change helps giving better visibility, by allowing to change the style of the kubernetes module in the prompt to draw attention, or changing the color to red (as an example) if using a context that should be used with care.

Closes #570 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Screenshots (if appropriate):
Screen Shot 2019-10-28 at 11 36 26

#### How Has This Been Tested?

- [X] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [X] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by nomaed** [comment]
Really not sure what's with with the Ubuntu and Windows test suites, failing on "setup python" steps... Would appreciate a hint or something.

```
Run actions/setup-python@v1
  with:
    python-version: 3.7.4
    architecture: x64
  env:
    GOROOT: /opt/hostedtoolcache/go/1.12.1/x64
##[error]Version 3.7.4 with arch x64 not found
Available versions:

2.7.16 (x64)
3.5.7 (x64)
3.6.9 (x64)
3.7.5 (x64)
3.8.0 (x64)
##[error]Node run failed with exit code 1
```

**Comment by nomaed** [comment]
I see that Python on Ubuntu & Windows have been failing for 3 days so I assume this is environmental, right? Missing image after some Python version update on the build servers or something?

**Comment by tracker1** [comment]
@nomaed Should probably bump the python version to `3.7.5` or `3.8.0` the version set is likely deprecated.

**Comment by johnletey** [comment]
@nomaed @tracker1 This is problem that @matchai and I have noticed. Take a look at https://github.com/actions/setup-python/issues/34. It's an issue that will keep happening as long as the GitHub Actions tool cache works the way it does. Matan has spoken to folks on the Actions team and let them know that it's painful for maintainers, and they will be fixing it, but not any time soon. So we have to wait for the tool caches for all OSes to be updated, before we can address this issue.

**Comment by acim** [comment]
Is this going to close #464 as well?

**Comment by nomaed** [comment]
@acim no, I didn't do any changes in that part

**Comment by Jacobious52** [comment]
Hi! Any update on this? Love this feature, been using it on a manual build for a while now. Would be awesome to have in the upstream version!

**Comment by nomaed** [comment]
I rebased the code and the build passed.
I've been using this new config for months now, from my branch. Would be happy if this gets into the main version :)

**Comment by pnehrer** [comment]
This is exactly the feature I was looking for! What's the plan for merging this in?

**Comment by mmatthews06** [comment]
This looks like a pretty cool feature!

**Comment by d33pcore** [comment]
Hey, would really like this feature to be merged! thanks!

**Comment by chipbuster** [comment]
Hey all,

Here's the deal with this PR right now: the mission control team unanimously voted to merge this, both because it's a useful feature and because it provides templates for how to implement future functionality.

Unfortunately, this PR is really, *really* old. It references testing functionality that hasn't existed in the starship codebase for years. Put simply, it can't be merged in its current state.

I've taken a few stabs at rebasing this myself, but unfortunately my spare time is limited right now, and rebasing this kind of thing tends to be more of an "understand exactly how this feature was written and the motivations, then completely rewrite it on top of the existing codebase" operation than a "run `git rebase` and resolve merge conflicts" operation. I keep running out of time, having to leave it, and by the time I come back two weeks later, I've completely forgotten how it's supposed to work.

So, this is where we're at: if someone wants to take it upon themselves to rebase this PR onto master, or write a PR based on this one, I will happily review it. We would, of course, also give @nomaed credit in the new set of commits.

If that doesn't happen in some amount of time (let's tentatively say by the end of April 2023), I'm going to declare the PR staled and close it, and we'll hope that someone else can come through and re-implement the feature over the current codebase.

My apologies to @nomaed for letting this rot in review hell for so long.

**Comment by nomaed** [comment]
I'm glad that this might get in. The code changes are pretty small so it's probably easiest to reimplement this in the current codebase. Personally, I don't know if or when I'll have a chance to do that, so hopefully someone more experienced can do that sooner.

**Comment by jankatins** [comment]
@chipbuster What is a good template to lookup the current way of testing? the [AWS module](https://github.com/starship/starship/blob/master/src/modules/aws.rs) and using the [src/test/... fixture handling](https://github.com/starship/starship/blob/master/src/test/mod.rs)??

**Comment by jankatins** [comment]
How does this relate to https://github.com/starship/starship/pull/1568/ (by @lht) -> Seems to do much the same: different styling for different environments?

(also partially to https://github.com/starship/starship/pull/4505, which allows to ignore some environments and has a nice test pattern for writing temp KUBECONFIG files)

**Comment by jankatins** [comment]
Also pinging @davidkna ...

Can anyone of the maintainer say which approach (between #614 and https://github.com/starship/starship/pull/1568) should be taken? I might have some time on Friday for this and I would like to ave this at $work :-)

**Comment by jankatins** [comment]
Oh, didn't know that, seems I will have some satisfying changes of my toml configs in front of me :-)

Ok, so todo:
- [ ] Rebase codebase in #614 on to of current HEAD
- [ ] Fix tests to conform to the current test best practices (main things: inlining into the main file, fixture from inline string? + fixing all brokenness)
- [ ] Add regex feature from #1568
- [ ] Make sure to keep the authorship/credits in the commits

**Comment by chipbuster** [comment]
@jankatins We're going to squash-and-rebase when merging, so I wouldn't worry so much about your last item. I seem to recall from the work on qrxyip's Rust branch that even if you lose all the authorship information, it can be added back in-post.

(If you can keep the information, it'd be nice to have, but don't sweat losing it).

**Comment by jankatins** [comment]
See https://github.com/starship/starship/pull/4550 for an updated/combined PR (#614 + #4505)

**Pull request closed without merging**
