### PR TITLE
fix(bash): Restore previous exit status in bash init

### LINKED ISSUE #2918: starship_precmd should restore previous exit status
#### Current Behavior
In bash, starship defines a `starship_precmd` function and adds it to `$PROMPT_COMMAND`. This command reads the last exit status, but it doesn't restore it when it's done. This means if I add another `$PROMPT_COMMAND` function after it that also cares about exit status, it will get the wrong status.

Compare this with `direnv`'s hook, which ends its function with `return $previous_exit_status` to restore the old status.

#### Expected Behavior
`starship_precmd` should return the previous status so any chained prompt command after it can still read it.

Unfortunately I'm not aware of any way to restore `$PIPESTATUS`.

#### Environment
- Starship version: 0.55.0
- bash version: GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.7.0)
- Operating system: Mac OS 11.4.0
- Terminal emulator: Apple_Terminal 440
- Git Commit Hash: 
- Branch/Tag: 
- Rust Version: rustc 1.53.0
- Rust channel:  release
- Build Time: 2021-06-30 05:44:17
#### Relevant Shell Configuration

```bash
#!/nix/store/6s8ccvhxm02hyr32jgy10md85zqbyv51-bash-4.4-p23/bin/bash

# […]

eval "$(/nix/store/5rbsk75nq49j5vh3n9w2icnfgd0jxp3x-direnv-2.28.0/bin/direnv hook bash)"
```

#### Starship Configuration

```toml
add_newline = false

[aws]
disabled = true
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"
symbol = "  "

[battery]
disabled = true

[cmake]
format = "\\[[$symbol($version)]($style)\\]"

[cmd_duration]
format = "[⏱ $duration]($style)"

[conda]
disabled = true
format = "\\[[$symbol$environment]($style)\\]"
symbol = " "

[crystal]
format = "\\[[$symbol($version)]($style)\\]"

[dart]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[deno]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"

[directory]
fish_style_pwd_dir_length = 1
read_only = " "
truncation_length = 1

[docker_context]
format = "\\[[$symbol$context]($style)\\]"
symbol = " "

[dotnet]
disabled = true
format = "\\[[$symbol($version)(🎯 $tfm)]($style)\\]"

[elixir]
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"
symbol = " "

[elm]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[erlang]
format = "\\[[$symbol($version)]($style)\\]"

[gcloud]
disabled = true
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"

[git_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = " "

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[golang]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[helm]
format = "\\[[$symbol($version)]($style)\\]"

[hg_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = " "

[java]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[julia]
disabled = true
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[kotlin]
format = "\\[[$symbol($version)]($style)\\]"

[kubernetes]
format = "\\[[$symbol$context( \\($namespace\\))]($style)\\]"

[lua]
format = "\\[[$symbol($version)]($style)\\]"

[memory_usage]
format = "\\[$symbol[$ram( | $swap)]($style)\\]"
symbol = " "

[nim]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[nix_shell]
format = "\\[[$symbol$state( \\($name\\))]($style)\\]"
symbol = " "

[nodejs]
format = "\\[[$symbol($version)]($style)\\]"

[ocaml]
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"

[openstack]
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"

[package]
format = "\\[[$symbol$version]($style)\\]"
symbol = " "

[perl]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[php]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[purescript]
format = "\\[[$symbol($version)]($style)\\]"

[python]
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"
symbol = " "

[red]
format = "\\[[$symbol($version)]($style)\\]"

[rlang]
detect_files = []

[ruby]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[rust]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[scala]
format = "\\[[$symbol($version)]($style)\\]"
symbol = " "

[shell]
bash_indicator = "$_"
disabled = false
fish_indicator = ""

[shlvl]
symbol = " "

[status]
disabled = false

[swift]
format = "\\[[$symbol($version)]($style)\\]"
symbol = "ﯣ "

[terraform]
format = "\\[[$symbol$workspace]($style)\\]"

[time]
format = "\\[[$time]($style)\\]"

[username]
format = "\\[[$user]($style)\\]"

[vagrant]
format = "\\[[$symbol($version)]($style)\\]"

[vcsh]
disabled = true

[vlang]
format = "\\[[$symbol($version)]($style)\\]"

[zig]
format = "\\[[$symbol($version)]($style)\\]"

```

### PR DESCRIPTION
**Pull request by chipbuster**
#### Description
Restore the previous exit status so that any subsequent hooks in the PROMPT_COMMAND pipeline can run with the correct return code.

#### Motivation and Context

Closes #2918

#### How Has This Been Tested?

I've confirmed that this doesn't negatively affect bash init, but I haven't confirmed that this actually causes the behavior intended. The fix is based on a comment by lilyball on the linked issue.

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by andytom — APPROVED** [review]

**Comment by chipbuster** [comment]
I can't request changes on my on my own PR, but I can merge it without an approving review? What??

Anyways, some testing has revealed that this does not entirely solve the linked issue, so let's not merge this until I've had a chance to test it more thoroughly.

**Review by andytom — CHANGES_REQUESTED** [review]
Blocking for now

**Comment by andytom** [comment]
> I can't request changes on my on my own PR, but I can merge it without an approving review? What??
> 
> Anyways, some testing has revealed that this does not entirely solve the linked issue, so let's not merge this until I've had a chance to test it more thoroughly.

Ooo interesting what are the problems it seemed to work fine for me locally, I only did a wee bit of testing so maybe I missed something.

**Comment by chipbuster** [comment]
Here's what I used to test, starting up from a shell with (almost) no config:

```
derp(){ echo "Previous exit was $?"; }
PROMPT_COMMAND=derp

# Separate commands, should result in exit codes of 0, 1, and 127
true
false
doesnotexist

eval "$(starship init bash)"

true
false
doesnotexist
```

With the previous version, after `starship init bash`, on my system, I would always get "Previous exit was 0".

Shell version is GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

**Comment by chipbuster** [comment]
Okay, I *think* this fixes the problem I saw.

**Review by andytom — APPROVED** [review]

**Pull request merged**
