### PR TITLE
fix(utils): reduce log level of errors in utils.

### LINKED ISSUE #1701: Executing command "node" failed by: Os
#### Current Behavior
When I open a prompt, first time, inside a node project, I get this error.
```sh
[WARN] - (starship::utils): Executing command "node" failed by: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

#### Expected Behavior
Shouldn't throw any error, even if something loaded lazily. Behaviour similar to `v0.44.0`.

#### Additional context/Screenshots
I am facing this issue after I updated from `v0.44.0` to `v0.45.0`. But with `v0.44.0` everything was working flawlessly.
I use [zinit](https://github.com/zdharma/zinit) to manage my `zsh` and I lazy load some program which modifies the path.

**Screenshot**
image

#### Environment
- Starship version: starship 0.45.0
- Shell type: zsh
- Shell version: zsh 5.8 (x86_64-pc-linux-gnu)
- Shell plugin manager: zinit
- Terminal emulator: Alacritty
- Operating system: Linux

#### Relevant Shell Configuration

```zsh
#!/bin/zsh

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

#####################
# PROMPT            #
#####################
zinit ice from"gh-r" as"command" atload'eval "$(starship init zsh)"'
zinit load starship/starship


##########################
# OMZ Libs and Plugins   #
##########################

# IMPORTANT:
# Ohmyzsh plugins and libs are loaded first as some these sets some defaults which are required later on.
# Otherwise something will look messed up
# ie. some settings help zsh-autosuggestions to clear after tab completion

setopt promptsubst

# Explanation:
# - Loading tmux first, to prevent jumps when tmux is loaded after .zshrc
# - History plugin is loaded early (as it has some defaults) to prevent empty history stack for other plugins
zinit lucid for \
    atinit"
        ZSH_TMUX_FIXTERM=true
        ZSH_TMUX_AUTOSTART=true
        ZSH_TMUX_AUTOCONNECT=true
    " \
    OMZP::tmux \
    atinit"HIST_STAMPS=dd.mm.yyyy" \
    OMZL::history.zsh \


zinit wait lucid for \
	OMZL::clipboard.zsh \
	OMZL::compfix.zsh \
	OMZL::completion.zsh \
	OMZL::correction.zsh \
    atload"
        alias ..='cd ..'
        alias ...='cd ../..'
        alias ....='cd ../../..'
        alias .....='cd ../../../..'
    " \
	OMZL::directories.zsh \
	OMZL::git.zsh \
	OMZL::grep.zsh \
	OMZL::key-bindings.zsh \
	OMZL::spectrum.zsh \
	OMZL::termsupport.zsh \
    atload"
        alias gcd='gco dev'
    " \
	OMZP::git \
	OMZP::fzf \
    atload"
        alias dcupb='docker-compose up --build'
    " \
	OMZP::docker-compose \
	as"completion" \
    OMZP::docker/_docker \
    djui/alias-tips \
    # hlissner/zsh-autopair \
    # chriskempson/base16-shell \

#####################
# PLUGINS           #
#####################
# @source: https://github.com/crivotz/dot_files/blob/master/linux/zplugin/zshrc

# IMPORTANT:
# These plugins should be loaded after ohmyzsh plugins

zinit wait lucid for \
    light-mode atinit"ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20" atload"_zsh_autosuggest_start" \
        zsh-users/zsh-autosuggestions \
    light-mode atinit"
        typeset -gA FAST_HIGHLIGHT;
        FAST_HIGHLIGHT[git-cmsg-len]=100;
        zpcompinit;
        zpcdreplay;
    " \
        zdharma/fast-syntax-highlighting \
    light-mode blockf atpull'zinit creinstall -q .' \
    atinit"
        zstyle ':completion:*' completer _expand _complete _ignored _approximate
        zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
        zstyle ':completion:*' menu select=2
        zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
        zstyle ':completion:*:descriptions' format '-- %d --'
        zstyle ':completion:*:processes' command 'ps -au$USER'
        zstyle ':completion:complete:*:options' sort false
        zstyle ':fzf-tab:complete:_zlua:*' query-string input
        zstyle ':completion:*:*:*:*:processes' command 'ps -u $USER -o pid,user,comm,cmd -w -w'
        zstyle ':fzf-tab:complete:kill:argument-rest' extra-opts --preview=$extract'ps --pid=$in[(w)1] -o cmd --no-headers -w -w' --preview-window=down:3:wrap
        zstyle ':fzf-tab:complete:cd:*' extra-opts --preview=$extract'exa -1 --color=always ${~ctxt[hpre]}$in'
    " \
        zsh-users/zsh-completions \
    bindmap"^R -> ^H" atinit"
        zstyle :history-search-multi-word page-size 10
        zstyle :history-search-multi-word highlight-color fg=red,bold
        zstyle :plugin:history-search-multi-word reset-prompt-protect 1
    " \
        zdharma/history-search-multi-word \
    reset \
    atclone"local P=${${(M)OSTYPE:#*darwin*}:+g}
            \${P}sed -i \
            '/DIR/c\DIR 38;5;63;1' LS_COLORS; \
            \${P}dircolors -b LS_COLORS > c.zsh" \
    atpull'%atclone' pick"c.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”' \
        trapd00r/LS_COLORS

#####################
# PROGRAMS          #
#####################

# A fork of `z' by rupa deadwyler with much improved zsh/bash completion and better results. The data file format and core algorithm are compatible with those of the original.
zinit wait'1' lucid light-mode for \
    pick"z.sh" \
    knu/z \
    as'command' atinit'export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"' pick"bin/n" \
    tj/n \
    from'gh-r' as'command' atinit'export PATH="$HOME/.yarn/bin:$PATH"' mv'yarn* -> yarn' pick"yarn/bin/yarn" bpick'*.tar.gz' \
    yarnpkg/yarn \

#####################
# ENV VARIABLE      #
#####################
export ZSH_AUTOSUGGEST_MANUAL_REBIND=1  # make prompt faster
export DISABLE_MAGIC_FUNCTIONS=true     # make pasting into terminal faster
export EDITOR=nvim
export PAGER=bat
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

#####################
# ALIASES           #
#####################
alias vim=$EDITOR
alias cat=bat
alias tf=terraform
alias l="exa -abghHlS --git --group-directories-first"
alias myip=ip-internal
alias sysinfo="inxi -Fxxxz"
alias psqlstart="sudo systemctl start postgresql.service"
alias h="http"

alias checkup="sudo pamac checkupdates -a"
alias up="pamac upgrade -a --no-confirm"
alias upnup="sudo pacman -Syyuu"
alias cleanup="sudo pacman -Rsn $(pacman -Qdtq)"
alias buildup="pamac build --no-confirm"
alias npmnuke="echo Deleting ^/node_modules/ && rm -rf ./**/node_modules"

#####################
# FZF SETTINGS      #
#####################
FD_OPTIONS="--hidden --follow"
export FZF_DEFAULT_OPTS="--prompt '⯈ ' --marker=+ --color=dark --layout=reverse --color=fg:250,fg+:15,hl:203,hl+:203 --color=info:100,pointer:15,marker:220,spinner:11,header:-1,gutter:-1,prompt:15"
export FZF_DEFAULT_COMMAND="fd --type f --type l $FD_OPTIONS || git ls-files --cached --others --exclude-standard"
export FZF_CTRL_T_COMMAND="fd $FD_OPTIONS"
export FZF_ALT_C_COMMAND="fd --type d $FD_OPTIONS"
export FZF_COMPLETION_OPTS="-x"

_fzf_compgen_path() {
    fd --hidden --follow . "$1"
}
_fzf_compgen_dir() {
    fd --type d --hidden --follow . "$1"
}

#####################
# GO SETTINGS       #
#####################
export CGO_ENABLED=1
export CGO_CFLAGS="-g -O2 -Wno-return-local-addr"
export GOPATH="$HOME/go/"
export PATH="$GOPATH/bin:$PATH"


#####################
# Functions         #
#####################
# echo "Ethernet :: IP => $( ip -4 -o a show wlan1 | awk '{ print $4 }' )"
ip-internal() echo "Wireless :: IP => $( ip -4 -o a show wlo1 | awk '{ print $4 }' )"
ip-external() echo "External :: IP => $( curl --silent https://ifconfig.me )"
ipinfo() { ip-internal && ip-external }

prcreate() gh pr create -B "$1" -f
prmerge() gh pr merge --merge --delete-branch=false "$1"
prlist() gh pr list --state open
prcheck() { gh pr checkout "$1" && gh pr diff }

#####################
# Misc Stuff        #
#####################

zinit is-snippet for \
    if"[[ -f $HOME/.localrc  ]]" $HOME/.localrc

```

#### Starship Configuration

```yaml
[cmd_duration]
disabled = true

[character]
success_symbol = "[❯](bold white)"

[aws]
disabled = true

[package]
display_private = true

# Starship doesn't have any module for showing docker symbol
# Issue: https://github.com/starship/starship/issues/393
[custom.docker]
description = "Shows the docker symbol if the current directory has Dockerfile or docker-compose.{yml,yaml} files"
when = """ command -v docker &> /dev/null; exit (echo $?); """
command = "echo 🐳"
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
format = "in [$output]($style)"
```

Edit:
I just noticed that with `v0.44.0` It doesn't throw any error but It also doesn't render the node symbol on the first prompt. Which, I believe because of the lazy loading of `n` (node version manager). After `n` is loaded node symbol appears.

### LINKED ISSUE #1723: Error when ocaml is missing
#### Current Behavior

Giving error message for lack of `ocaml`:

```
[WARN] - (starship::utils): Executing command "ocaml" failed by: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

#### Expected Behavior

No error message.

#### Environment
- Starship version: starship 0.45.2
- Shell type: zsh
- Shell version: zsh 5.8 (x86_64-pc-linux-gnu)
- Shell plugin manager: antibody
- Terminal emulator: Alacritty
- Operating system: ArchLinux

#### Relevant Shell Configuration

Nothing relevant.

#### Starship Configuration

Not relevant. There's only unicode glyph settings, none refers to anything ocaml related.

### PR DESCRIPTION
**Pull request by andytom**
#### Description

Have reduced the log level when we fail to execute a command since this
is happening a lot more that expected, for example if a user checks out
a repo that contains a `.js` file but they don't have node installed.

#### Motivation and Context

Closes #1723 
Closes #1701 

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by ATiltedTree — APPROVED** [review]
I didn't really think about it too much when I made that change. But now I see why these errors can get annoying. LGTM :+1:

**Comment by andytom** [comment]
> I didn't really think about it too much when I made that change. But now I see why these errors can get annoying. LGTM +1

No worries, I didn't think about it that much either until I saw we had a few issues about this.

**Comment by MunifTanjim** [comment]
Can we please cut a release with this? 😅

**Comment by matchai** [comment]
Whoops! I totally thought this was included in the last release.
Will do! 👍

**Pull request merged**
