### PR TITLE
fix: Remove duplicate space in default symbol for the Gcloud plugin

### PR DESCRIPTION
**Pull request by mdryden**
The default symbol value has an extra space, making it look different than other default configurations.

#### Description

The default symbol value has an extra space, making it look different than other default configurations.

#### Motivation and Context

The default looks mis-aligned and doesn't fit with the other defaults as far as I can tell.  It also doesn't match what the documents claim that it is (cloud icon with a single space).

#### Screenshots (if appropriate):

image

#### How Has This Been Tested?

I have not manually built starship, so I have not tested this change directly.  I have tested the corrected symbol by overriding in my toml file, which works as expected.

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by mdryden** [comment]
I see that there were some unit tests here which must have been coded to use the extra space.  I can take a shot at fixing those and re-submitting.

**Comment by chipbuster** [comment]
This was part of a fix made in #2666. See [this link](https://github.com/starship/starship/issues/2616#issuecomment-829338508) for more details on why it was necessary.

The short version is that without this, certain terminals cannot correctly display double-width emoji, and we consider it better to have uneven spacing by default than to break rendering by default.

**Comment by mdryden** [comment]
I see, thank-you for the explanation, @chipbuster.

I will close the pull request, as I can't dedicate the time to try and change the implementation.  I guess the toml override will have to do :)

**Comment by mdryden** [comment]
Just an update for anyone who googles this up...

I noticed the double space on Konsole, which I was using as my primary terminal, but then when I enabled starship in the VSCode terminal, I saw it with only a single space (as described in the related issue).

I tested a few more terminals, and decided to ditch Konsole rather than editing the toml file, because it seemed easier than trying to change the behavior on VSCode.

Some test results:
Konsole - two spaces
Gnome Terminal - one space
VSCode Terminal - one space
XFCE Terminal - one space

**Pull request closed without merging**
