### PR TITLE
fix(docs): "Command Duration" section link target

### PR DESCRIPTION
**Pull request by cmarqu**
#### Description

Change case of reference to match what is needed.

#### Motivation and Context

The correct doc location isn't opened otherwise.

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by davidkna** [comment]
Thanks for the contribution @cmarqu,  to get the CI to pass can you either update your commit message to include the prefix `fix:` in the title or just push an empty commit to this branch e.g

```sh
git commit --allow-empty -m 'make Semantic PR bot happy'
git push 
```

**Comment by cmarqu** [comment]
Done.

**Review by andytom — APPROVED** [review]
LGTM

**Comment by andytom** [comment]
Thank you for your contribution @cmarqu

**Pull request merged**
