### PR TITLE
feat(java): Add `.sdkmanrc` for Java

### PR DESCRIPTION
**Pull request by iuhoay**
#### Description

Add https://sdkman.io/ for Java. If a `.sdkmanrc` file is present, show the Java version.

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Review by davidkna — APPROVED** [review]
Please also update the table in the English java module docs.

**Review by davidkna — CHANGES_REQUESTED** [review]
Please also update the table in the English java module docs.

**Comment by iuhoay** [comment]
@davidkna Doc is updated.

**Review by davidkna — APPROVED** [review]

**Comment by davidkna** [comment]
Thanks for the contribution @iuhoay!

**Pull request merged**
