### PR TITLE
docs: fix typo `moudle` -> `module`

### PR DESCRIPTION
**Pull request by erikphansen**
#### Description

This fixes a typo that exists in multiple README files.

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by vladimyr** [comment]
I believe you shouldn't manually update translated docs, it is done automatically, right @andytom? :thinking:

**Comment by erikphansen** [comment]
Ah, well, someone who is more in the know should feel free to close this PR and make the fix the correct way :)

**Comment by andytom** [comment]
> I believe you shouldn't manually update translated docs, it is done automatically, right @andytom? :thinking: 

Yep, you only need to update the English version of the docs the non-English versions will be updated automatically by [Crowdin](https://translate.starship.rs).

**Comment by vladimyr** [comment]
> Ah, well, someone who is more in the know should feel free to close this PR and make the fix the correct way :)

Closing in favor of #2504
@erikphansen Thank you for your contribution! :+1:

**Pull request closed without merging**
