### PR TITLE
refactor(nodejs): Use format strings

### PR DESCRIPTION
**Pull request by jletey**
#### Description

This PR deprecates `symbol` `style` keys in `NodejsConfig`, and adds `format` key instead.

Based off of #1063.

#### Motivation and Context

Related #1057

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Screenshots (if appropriate):

Screenshot 2020-04-08 at 16 10 37

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by jimleroyer** [comment]
Let's not forget to update the documentation in the `docs\config\README.md` file as showed in this PR:
https://github.com/starship/starship/pull/1063

📚 🤓

**Comment by jletey** [comment]
This should be ready to merge folks 👍

**Comment by andytom** [comment]
Thanks for the contribution @jletey

**Comment by jletey** [comment]
@andytom My pleasure 😊

**Pull request merged**
