### PR TITLE
fix: update python to v3.7.5

### PR DESCRIPTION
**Pull request by spk**
#### Description

Update python to v3.7.5

#### Motivation and Context

 To update CI on https://github.com/starship/starship/pull/617

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by johnletey** [comment]
@spk As I said in https://github.com/starship/starship/pull/614#issuecomment-549018461:

> This is problem that @matchai and I have noticed. Take a look at [actions/setup-python#34](https://github.com/actions/setup-python/issues/34). It's an issue that will keep happening as long as the GitHub Actions tool cache works the way it does. Matan has spoken to folks on the Actions team and let them know that it's painful for maintainers, and they will be fixing it, but not any time soon. So we have to wait for the tool caches for all OSes to be updated, before we can address this issue.

**Comment by nomaed** [comment]
While it is best to use exactly the same version for all tests (including the patch version), would it not be reasonable to set the version to `3.7.x` for the time being, until the problem is solved?

I would _assume_ that this should not have negative consequences on the quality of the tests.

**Comment by matchai** [comment]
Our tests generate the prompt based on the version of a runtime that is installed on the machine. We would need fixed versions on all platforms for our tests to pass the way they are right now.
This will not be a problem if we get around to addressing #289.

**Comment by matchai** [comment]
Closing this PR until the tool cache is updated to add Python v3.7.5 support on all OSes.

**Pull request closed without merging**
