### PR TITLE
fix: update continuation prompt to be more minimal

### PR DESCRIPTION
**Pull request by matchai**
#### Description

This PR updates the continuation prompt to be a more minimal alternative to the current yellow chevron.

I think the yellow chevron may be a little bold and visually loud for something that I feel is more of an accent than an actionable piece of information. Interested to hear your thoughts @raccog, @chipbuster, @davidkna.

**Changes**
- Replace the chevron with a gray (bright black) bullet
- Add a space after the prompt to better align with the default prompt

#### Motivation and Context

Closes #

#### Screenshots (if appropriate):

**Current continuation prompt defaults**
CleanShot 2022-01-01 at 16 56 03@2x

**Proposed update**
CleanShot 2022-01-01 at 16 57 23@2x

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by davidkna** [comment]
I would also prefer this as the default.

**Comment by raccog** [comment]
Looks good to me! I like that the circle differentiates it from a normal prompt.

I also noticed that I forgot to include a space after the arrow, so thank you for fixing that!

**Comment by matchai** [comment]
Alternatively, we could go even smaller with the "dot product" symbol, which I think I prefer.

<table>
<tr>
	<td>Bullet
	<td>Dot product
<tr>
	<td>CleanShot 2022-01-01 at 16 57 23@2x
	<td>CleanShot 2022-01-01 at 17 29 22@2x

</table>

**Comment by chipbuster** [comment]
I like the look.

**Pull request merged**
