### PR TITLE
Translated requirements.

### PR DESCRIPTION
**Pull request by emorozov**
Translated requirements in the Russian docs.

### CODE REVIEW

**Comment by mickimnet** [comment]
Hello @emorozov,
thank you very, very much for your update on the translation of the requirements section in Russian.

All translations for the documentation are done through the system [Crowdin](https://translate.starship.rs/project/starship-prompt), and automatically generated and included in the language sections.

Could you be please so kind and change/suggest the changes at [Crowdin](https://translate.starship.rs/project/starship-prompt)?

Thanks a lot and take care!

**Comment by emorozov** [comment]
Ah, sorry, that wasn't obvious to me. I will close this PR.
I'll try to register for the crowd translation project later.

**Comment by mickimnet** [comment]
Thank you very much!

**Comment by nesara-cmd** [comment]
👍

**Pull request closed without merging**
