### PR TITLE
feat(git_branch): add remote branch name if different than local branch

### LINKED ISSUE #1757: Show Git remote tracking branch
## Feature Request

It would be cool if the git_branch can also show the remote tracking branch in case the current branch is named differently than the remote tracking one,

#### Is your feature request related to a problem? Please describe.

No problem. Just a convenience.

#### Describe the solution you'd like

`michele in xray in /tmp/starship on  development:remote_dev_branch %`

#### Describe alternatives you've considered

No alternative.

### PR DESCRIPTION
**Pull request by sagittarius-a**
#### Description

Show the remote tracking branch in case the current branch is named differently than the remote tracking one.

The remote branch name is appended to the branch name, separated by a `:`, as stated in the issue linked below.

#### Motivation and Context

Closes #1757

#### Screenshots (if appropriate):
Before
image

After
image

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [X] I have tested using **Windows**

#### Checklist:

- [X] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by jimleroyer** [comment]
It is using a flag variable to show the remote branch, rather than using two different variables for both local and remote branches as seemingly agreed in the issue #1757 . It would offer more user's customization doing so. Can we do it this way? or might be I missed a conversation, which in that case, feel free to redirect me to.

**Comment by sagittarius-a** [comment]
I have implemented it as agreed in #1757. Now I need to write some tests and I guess the PR would be complete.

**Review by andytom — APPROVED** [review]
LGTM, looks like we have some merge conflicts if you can fix these @sagittarius-a I think we should be good to go here.

**Comment by sagittarius-a** [comment]
Rebased my work on master. Should be ok now. (minus the failing job)

**Comment by andytom** [comment]
Thank you for your contribution @sagittarius-a

**Comment by mbologna** [comment]
Thank you @sagittarius-a :1st_place_medal: !

**Pull request merged**
