### PR TITLE
refactor(nu): simplify getting term width

### PR DESCRIPTION
**Pull request by verdayne**
#### Description

[starship.nu L11](https://github.com/starship/starship/blob/0b173c263e510be572db3ac88f3df7ca01aa486a/src/init/starship.nu#L11) uses multiple piping commands to pull the terminal width from `term size` and convert the result into a string. These actions can be condensed and combined into one of nushell's subexpressions, which makes the code cleaner and easier to read. The proposal is shown below.

Before:
```nu
let width = (term size | get columns | into string)
```
After:
```nu
let width = (term size).columns
```

#### Motivation and Context

Remove piping chain and reduce points of failure to only `term size` and the requested value `columns`.

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by davidkna — APPROVED** [review]

**Comment by mati865** [comment]
This does fix the error when  using the latest release of Nushell, can it be merged?

**Comment by davidkna** [comment]
@mati865 It's already fixed on the master branch.

**Comment by mati865** [comment]
Right, sorry. Mislooked at the diff.

**Comment by davidkna** [comment]
Thanks for the clean-up @verdayne!

**Comment by verdayne** [comment]
@davidkna thank you for accepting my suggestion

**Pull request merged**
