### PR TITLE
ci: continue release on error

### PR DESCRIPTION
**Pull request by matchai**
#### Description

During the release process, if a build fails, the whole release process is thrown out the window.
This will cause the release to proceed with the artifacts that are correctly built.

### CODE REVIEW

**Comment by davidkna** [comment]
How did the build end up failing? Can't see the logs for it. I also just noticed the build cache is still enabled in the release workflow. Could that have been the cause?

**Review by davidkna — APPROVED** [review]

**Comment by andytom** [comment]
> How did the build end up failing? Can't see the logs for it. I also just noticed the build cache is still enabled in the release workflow. Could that have been the cause?

It was a problem with the runner, macOS 11 is in private preview so only some organisations or users can use it and it doesn't seem like we are one of the lucky ones :disappointed:

**Comment by davidkna** [comment]
Looks like I tested it when enrolment was open and they've closed it now.

**Comment by matchai** [comment]
I've updated the PR to temporarily disable aarch64-apple-darwin builds.

**Review by andytom — APPROVED** [review]
LGTM

**Pull request merged**
