### PR TITLE
docs: added winget

### PR DESCRIPTION
**Pull request by shafschwd**
#### Description
added [Winget](https://github.com/microsoft/winget-cli) as a installation method in the doc

#### Motivation and Context
winget is the official package manager for windows and its installed by default so user's don't have to install other 3rd party package manager such as `scoop` or `chocolatey`  

> which are great package managers

to install starship

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by jeffhandley — APPROVED** [review]
I just successfully installed starship using winget. I was going to submit a PR to add this to the website, but I found this PR is already open.

**Review by davidkna — CHANGES_REQUESTED** [review]
This seems fine, but please remove the scoop instructions above.

**Review by shafschwd — COMMENTED** [review]
removed scoop instruction

**Comment by andytom** [comment]
Thanks for your contribution @shafschwd.

**Pull request merged**
