### PR TITLE
fix: Add disable option to kubernetes module

### PR DESCRIPTION
**Pull request by heyrict**
#### Description
This PR adds one line to skip the module if it is not enabled in the config.
It also renames `fn is_module_enabled` to better reflex its functionality.

#### Motivation and Context
I used to think `is_module_enabled` has a higher order functionality to judge if the module is disabled, but it turns out it only reads the user's config and ignores the default one. (Thanks to @andytom to point it out!)
Related #484 #486 #489

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by heyrict** [comment]
Also note that, this is just a hot-fix. The `disabled` option doesn't seem to be quite neat.

`print.rs` can filter out modules with `disabled = false` in user's config. Thus all modules enabled by default will continue to work, but modules disabled by default will have to add an extra line to get it disabled.

**Comment by heyrict** [comment]
Another approach (as noted in discord) in brief is:

1. Add `fn is_disabled(&self) -> bool` to `trait RootModuleConfig`
1. Add `fn get_config(name: &str) -> Option<impl RootModuleConfig>` similar to `modules/mod.rs` to `configs/mod.rs`.
1. In `fn is_module_enabled`, use

    ```
    pub fn is_module_enabled(&self, name: &str) -> bool {
        let config = get_config(name);

        let disabled = config.and_then(|config| config.is_disabled());

        disabled == Some(true)
    }
    ```

**Comment by matchai** [comment]
That sounds solid to me.

**Comment by matchai** [comment]
Do you think this is something we can implement for this PR, or should I go ahead and merge this as it is?

**Comment by heyrict** [comment]
@matchai Well, This PR is just a quick fix. I think it should be merged to fix the regression first.
I'll open a new PR related to https://github.com/starship/starship/pull/491#issuecomment-538651086 if I have enough time.

**Pull request merged**
