### PR TITLE
docs: Update README.md with instructions for termux

### PR DESCRIPTION
**Pull request by gunslingerfry**
#### Description

Added install steps for termux

#### Motivation and Context

Easier install in termux

#### How Has This Been Tested?

- [X] I have tested using **Linux (Termux)**

#### Checklist:

- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by andytom** [comment]
Thanks for the contribution @gunslingerfry,  to get the CI to pass can you either update your commit message to include the prefix `docs:` in the title or just push an empty commit to this branch e.g

```
git commit --allow-empty -m 'make Semantic PR bot happy'
git push 
```

**Review by chipbuster — APPROVED** [review]
LGTM.

**Comment by vladimyr** [comment]
Is there a reason why we would favor this instead of using the official termux package which we already had mentioned inside our docs (got stripped in the removal of extra installation methods from README)?

**Comment by gunslingerfry** [comment]
Well, I'll be. Didn't realize there was an official termux package. I could 
have sworn I checked but perhaps I just followed the curl install 
instructions. The termux package is at 0.48, but I doubt that qualifies as 
a good enough reason. This change is  superfluous then.

**Comment by vladimyr** [comment]
No worries, it might be superfluous but still serves people better than lack of any guidance 😉

**Pull request merged**
