### PR TITLE
Distinguish between pwsh and powershell

### PR DESCRIPTION
**Pull request by HeyItsGilbert**
#### Description
pwsh.exe and powershell.exe are currently both identified as powershell. This PR intends to distinguish between the two in the shell module (as well as make the necessary context changes to allow for that)

This is a copy of #5031 which was in draft. Hopefully I did this right....

#### Motivation and Context
Distinguishes between pwsh and powershell shell instances. A Windows machine can have both and having a clear distinction can avoid issues.

Closes #5031 

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by HeyItsGilbert** [comment]
One obvious place this will likely need additional work is on all the help docs across the different languages. Just wanted to get an idea of I'm at least heading in the right direction before updating all of those. Thanks for starting this @wmmc88 !

**Comment by davidkna** [comment]
@HeyItsGilbert Translation is handled exclusively on crowdin. Regarding any new options, please keep them compatible with what is already there, e.g., by having any new option default to the old option value.

**Comment by HeyItsGilbert** [comment]
Reverted some of the renames to match the existing name. Tried to rebase and squash the commits. Hopefully I didn't screw it up.

**Comment by wmmc88** [comment]
hey @HeyItsGilbert! are you planning on landing this?

**Comment by HeyItsGilbert** [comment]
I think I was waiting on an approval. I'll rebase since this is super old. We'll see what the tests come back with.

**Comment by HeyItsGilbert** [comment]
Well I totally screwed up my rebase... I need to go RTFM on how to rebase. I made a huge mistake making my upstream be your change @wmmc88 . My bad.

**Comment by HeyItsGilbert** [comment]
Dumped my entire repo because I totally screwed it up. Fresh repo. #5478 is my do-over.

**Pull request closed without merging**
