### PR TITLE
feat: Update colors of package and php

### PR DESCRIPTION
**Pull request by matchai**
#### Description

This PR changes the colors of two modules:
- `package` red -> green
  Too many of the runtime modules are red, which makes the `package` module hard to read and distinguish from the runtime module. I propose we make it green so it will be a unique color compared to all the runtimes

  image

- `php` red -> purple
  PHP has a very identifiable purple logo. Why not make this module purple instead of _yet another red_ module?

  

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by matchai** [comment]
I didn't realize that the `nodejs` module is also green, which would make both `package` and `nodejs` green in a Node.js project. In that case, our color options for `package` can't be red (Rust), green (Node.js), yellow (Python), or purple (PHP).

Maybe a light brown or a blue? There needs to be more colors 😛

**Comment by chipbuster** [comment]
Would it be possible to check the status of `$COLORTERM` or similar and then set different palettes based on that? There's a pretty great overview of terminal color support on [this gist](https://gist.github.com/XVilka/8346728), and it looks like the only super common terminals (that I know of) that don't support true color are Hyper.js, MacOS Terminal, urxvt, and xterm.

I think we'd also want a way to fall back to just the 16-color scheme, since I think those are the only colors overridden by terminal themes (so anything outside of those colors won't be respecting the user's color theme choices)

**Comment by johnletey** [comment]
I personally don't use the PHP module, but love that purple 😍

I wouldn't be opposed to a light brown, but I agree, we definitely need more colours!

**Comment by matchai** [comment]
Maybe orange?

**Comment by johnletey** [comment]
> Maybe orange?

@matchai I'm a fan 😄

**Pull request merged**
