### PR TITLE
fix(cmake): Change cmake symbol

### LINKED ISSUE #2446: CMake incorrect CMake symbol
#### Current Behavior

The 喝-symbol is currently used for CMake, however this gives me a Chinese valid symbol in my terminal, but not the intended triangle. 

#### Expected Behavior

Instead, I expect a triangle symbol, so use the correct unicode symbol for a triangle. Instead try to use the following symbol '△'.

#### Additional context/Screenshots

image

### Solution

I created a Pull request to get this fixed. 

https://github.com/starship/starship/pull/2447

### PR DESCRIPTION
**Pull request by danger89**
Solves #2446

### CODE REVIEW

**Review by vladimyr — APPROVED** [review]

**Review by andytom — COMMENTED** [review]
For the documentation you only need to change the English version, all the other languages are handled automatically by [Crowdin](translate.starship.rs) can you remove the changes to the other languages as this can cause conflicts with CrowdIn's PRs.

**Comment by danger89** [comment]
Really? If that is true, why check them in.. How can you make differences between languages if it all comes from english?

**Comment by danger89** [comment]
Anyway, I have too many commits now. I will open a new PR.

**Review by chipbuster — CHANGES_REQUESTED** [review]
As andytom said, the other languages are managed by Crowdin. What happens is that the english-language version is submitted to the site, our community translators do their thing in a web interface, and then the changes are merged back in by a crowdin bot.

Editing the non-english docs directly on GitHub interferes with this last step, preventing it from being done automatically.

**Pull request closed without merging**
