### PR TITLE
[docs] Simplify Nushell integration

### PR DESCRIPTION
**Pull request by texastoland**
#### Description

Simplifies Nushell integration instructions *(docs only)* in the following ways:

- Saves the script to a standard cross-platform path
- Just `use starship.nu` instead of arbitrary path
- Provides runnable commands
- Explains why it's necessary 
- Explains how to update

#### Motivation and Context

Motivated by jdx/mise-docs#46 for consistency between tools.

#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly *(N/A)*.

### CODE REVIEW

**Review by davidkna — CHANGES_REQUESTED** [review]
It hasn't been more stable lately, but nushell has had many breaking changes and our init script also gets updated now and then, so I would like to avoid having the init script static at this time.

**Comment by texastoland** [comment]
> I would like to avoid having the init script static at this time.

It was already static. That's the same. I added a link to explain why:

```diff
+   Since Nu does [not support `eval`](https://www.nushell.sh/book/how_nushell_code_gets_run.html#eval-function) you must save the initialization script:
```

**Comment by davidkna** [comment]
FWIW, it is not necessarily static between different versions of starship (or with different starship binary locations).

More importantly, if the file doesn't update itself, it will make handling user issues more difficult and will cause additional strife on breaking nushell updates. Given all that, I'd rather not accept this PR.

**Comment by texastoland** [comment]
> * Saves the script to a standard cross-platform path
> * Just `use starship.nu` instead of arbitrary path
> * Provides runnable commands
> * Explains why it's necessary
> * Explains how to update

@davidkna I think you're misunderstanding. It is and always was "static" because Nu doesn't have an "eval" feature. My documentation only explains that and simplifies the process. Request to reopen CC @matchai.

**Pull request closed without merging**
